// =========================================================
// RUGBIX — BASE DE DONNÉES
// Les joueurs sont chargés depuis Google Sheets au démarrage.
// TEAMS, RARITIES et PACKS restent définis ici.
// =========================================================

// URL CSV du Google Sheet (doit être publié : Fichier → Partager → Publier sur le web → CSV)
const SHEET_CSV_URL = "https://docs.google.com/spreadsheets/d/1nYO8sQI0LV_0KaqU2hSo478yJTxlJGD-wFX6vHe1Ipg/pub?gid=0&single=true&output=csv";

const TEAMS = {
  
  "toulouse":   { name: "Stade Toulousain", color: "#cc0000" },
  "ubb":        { name: "Union Bordeaux-Bègles", color: "#73354C" },
  "racing92":   { name: "Racing 92", color: "#add7f3" },
  "lapelle":    { name: "Stade Rochelais", color: "#FFD000" },
  "toulon":     { name: "RC Toulon", color: "#BA0B12" },
  "clermont":   { name: "ASM Clermont Auvergne", color: "#FEEB2F" },
  "bayonne":    { name: "Aviron Bayonnais", color: "#7AB7E7" },
  "pau":        { name: "Section Paloise", color: "#007333" },
  "lyon":       { name: "Lyon OU", color: "#C9424A" },
  "castres":    { name: "Castres Olympique", color: "#A4B4CA" },
  "montpellier":{ name: "Montpellier Hérault Rugby", color:"#002958"},
  "stadefr":    { name: "Stade Français Paris", color: "#EC5E9D" },
  "perpignan":  { name: "USA Perpignan", color: "#db1d3a" },
  "montauban":  { name: "US Montauban", color: "#1A4934" }, // conservé en mémoire (remplacé par Vannes en TOP 14)
  "biarritz":   { name: "Biarritz Olympique", color: "#F20000" },
  "vannes":     { name: "Rugby Club Vannes", color: "#001438"  },
  "bourgoinjallieu": { name: "CS Bourgoin-Jallieu", color: "#003366" }
  
};

// Base de joueurs locale (fallback si Google Sheets indisponible)
const PLAYERS = [

  // ----- STADE TOULOUSAIN -----
  { name: "Cyril Baille", team: "toulouse", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Dorian Aldegheri", team: "toulouse", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Georges-Henri Colombe", team: "toulouse", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Benjamin Bertrand", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Rodrigue Neti", team: "toulouse", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Tom Rapetti", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "ARG" },
  { name: "David Ainu'u", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "USA" },
  { name: "Paul Mallez", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Joel Merkler", team: "toulouse", positions: ["Pilier", "Deuxième ligne"], rarity: "commune", nat: "ESP" },
  { name: "Malachi Hawkes", team: "toulouse", positions: ["Pilier", "Talonneur"], rarity: "commune", nat: "AUS" },
  { name: "Julien Marchand", team: "toulouse", positions: ["Talonneur"], rarity: "epique", nat: "FRA" },
  { name: "Peato Mauvaka", team: "toulouse", positions: ["Talonneur", "Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Guillaume Cramont", team: "bayonne", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Thomas Lacombre", team: "toulouse", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Thibaud Flament", team: "toulouse", positions: ["Deuxième ligne","Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Emmanuel Meafou", team: "toulouse", positions: ["Deuxième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Elias Efrain", team: "toulouse", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "commune", nat: "ARG" },
  { name: "Joshua Brennan", team: "toulouse", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Clément Vergé", team: "toulouse", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Alexandre Roumat", team: "toulouse", positions: ["Troisième ligne", "Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Romeo Bonnard Martin", team: "toulouse", positions: ["Troisième ligne", "Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "François Cros", team: "toulouse", positions: ["Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Anthony Jelonch", team: "toulouse", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Jack Willis", team: "toulouse", positions: ["Troisième ligne"], rarity: "epique", nat: "ANG" },
  { name: "Léo Banos", team: "toulouse", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mathis Castro-Ferreira", team: "toulouse", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Théo Ntamack", team: "toulouse", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Antoine Dupont", team: "toulouse", positions: ["Demi de mêlée"], rarity: "international", nat: "FRA" },
  { name: "Paul Graou", team: "toulouse", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Romain Ntamack", team: "toulouse", positions: ["Demi d'ouverture"], rarity: "epique", nat: "FRA" },
  { name: "Lucien Richardis", team: "toulouse", positions: ["Demi d'ouverture", "Arrière"], rarity: "commune", nat: "ESP" },
  { name: "Valentin Delpy", team: "toulouse", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Santiago Chocobares", team: "toulouse", positions: ["Centre"], rarity: "rare", nat: "ARG" },
  { name: "Paul Costes", team: "racing92", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Pierre-Louis Barassi", team: "toulouse", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Tommaso Menoncello", team: "toulouse", positions: ["Centre"], rarity: "rare", nat: "ITA" },
  { name: "Célian Pouzelgues", team: "toulouse", positions: ["Centre"], rarity: "commune", nat: "TGA" },
  { name: "Kalvin Gourgues", team: "toulouse", positions: ["Centre","Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Teddy Thomas", team: "toulouse", positions: ["Ailier", "Centre"], rarity: "rare", nat: "FRA" },
  { name: "Matthis Lebel", team: "toulouse", positions: ["Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Dimitri Delibes", team: "montpellier", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Nelson Épée", team: "toulouse", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Ramos", team: "toulouse", positions: ["Arrière", "Demi d'ouverture"], rarity: "international", nat: "FRA" },
  { name: "Blair Kinghorn", team: "toulouse", positions: ["Arrière", "Demi d'ouverture"], rarity: "rare", nat: "ECO" },
  { name: "Ange Capuozzo", team: "toulouse", positions: ["Arrière", "Ailier"], rarity: "epique", nat: "ITA" },
  { name: "Juan Cruz Mallia", team: "toulouse", positions: ["Arrière", "Ailier"], rarity: "epique", nat: "ARG" },
  { name: "Matias Remue", team: "toulouse", positions: ["Arrière"], rarity: "commune", nat: "BEL" },
  { name: "Thomas Alary", team: "toulouse", positions: ["Arrière"], rarity: "commune", nat: "FRA" },

  // ----- UNION BORDEAUX-BÈGLES -----
  { name: "Jefferson Poirot", team: "ubb", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Ben Tameifuna", team: "ubb", positions: ["Pilier"], rarity: "epique", nat: "TGA" },
  { name: "Sipili Falatea", team: "ubb", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Mathis Perchaud", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Zinedine Aouad", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Toma Taufa", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "TGA" },
  { name: "Ugo Boniface", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Carlü Sadie", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "AFS" },
  { name: "Lekso Kaulashvili", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Maxime Lamothe", team: "ubb", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Connor Sa", team: "ubb", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Gaëtan Barlot", team: "ubb", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Cameron Woki", team: "ubb", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Adam Coleman", team: "ubb", positions: ["Deuxième ligne"], rarity: "rare", nat: "AUS" },
  { name: "Alexander Moon", team: "ubb", positions: ["Deuxième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Cyril Cazeaux", team: "ubb", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Boris Palu", team: "ubb", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Pieter-Steph du Toit", team: "ubb", positions: ["Troisième ligne"], rarity: "epique", nat: "AFS" },
  { name: "Bastien Vergnes-Taillefer", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Pierre Bochaton", team: "ubb", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Jean-Luc Du Preez", team: "ubb", positions: ["Troisième ligne"], rarity: "rare", nat: "AFS" },
  { name: "Temo Matiu", team: "ubb", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Tiaan Jacobs", team: "ubb", positions: ["Troisième ligne"], rarity: "rare", nat: "AFS" },
  { name: "Marko Gazzotti", team: "ubb", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Lachlan Swinton", team: "perpignan", positions: ["Troisième ligne"], rarity: "commune", nat: "AUS" },
  { name: "Tom Willis", team: "ubb", positions: ["Troisième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Maxime Lucu", team: "ubb", positions: ["Demi de mêlée"], rarity: "epique", nat: "FRA" },
  { name: "Martin Page-Relo", team: "ubb", positions: ["Demi de mêlée"], rarity: "rare", nat: "ITA" },
  { name: "Valentin Hutteau", team: "ubb", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Matthieu Jalibert", team: "ubb", positions: ["Demi d'ouverture"], rarity: "international", nat: "FRA" },
  { name: "Hugo Reus", team: "ubb", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Yoram Moefana", team: "ubb", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Nicolas Depoortère", team: "ubb", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Ben Tapuai", team: "ubb", positions: ["Centre"], rarity: "commune", nat: "AUS" },
  { name: "Rohan Janse Van Rensburg", team: "ubb", positions: ["Centre"], rarity: "rare", nat: "AFS" },
  { name: "Adrien Drault", team: "ubb", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Pablo Uberti", team: "ubb", positions: ["Centre", "Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Arthur Retière", team: "ubb", positions: ["Ailier","Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Damian Penaud", team: "ubb", positions: ["Ailier", "Centre"], rarity: "epique", nat: "FRA" },
  { name: "Louis Bielle-Biarrey", team: "ubb", positions: ["Ailier", "Arrière"], rarity: "epique", nat: "FRA" },
  { name: "Salesi Rayasi", team: "ubb", positions: ["Ailier","Arrière"], rarity: "rare", nat: "FIJ" },
  { name: "Xan Mousques", team: "ubb", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Romain Buros", team: "ubb", positions: ["Arrière"], rarity: "rare", nat: "FRA" },
 

  // ----- USA PERPIGNAN -----
  { name: "Enzo Forletta", team: "perpignan", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Posolo Tuilagi", team: "perpignan", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Tom Ecochard", team: "perpignan", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Antoine Aucagne", team: "perpignan", positions: ["Demi d'ouverture","Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Jerónimo de la Fuente", team: "perpignan", positions: ["Centre"], rarity: "rare", nat: "ARG" },
  { name: "Jake McIntyre", team: "perpignan", positions: ["Demi d'ouverture", "Arrière"], rarity: "rare", nat: "AUS" },
  { name: "Alivereti Duguivalu", team: "stadefr", positions: ["Ailier", "Centre"], rarity: "rare", nat: "FIJ" },
  { name: "Joaquín Oviedo", team: "perpignan", positions: ["Troisième ligne"], rarity: "epique", nat: "ARG" },
  { name: "Ignacio Ruiz", team: "perpignan", positions: ["Talonneur"], rarity: "rare", nat: "ARG" },
  { name: "Giorgi Tetrashvili", team: "perpignan", positions: ["Pilier"], rarity: "rare", nat: "GEO" },
  { name: "Giorgi Beria", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Kieran Brookes", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "ANG" },
  { name: "Seilala Lam", team: "perpignan", positions: ["Talonneur"], rarity: "commune", nat: "SAM" },
  { name: "Victor Montgaillard", team: "perpignan", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Tristan Labouteley", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Jacobus van Tonder", team: "perpignan", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "commune", nat: "AFS" },
  { name: "Mathieu Tanguy", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Bruce Devaux", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Lorencio Boyer Gallardo", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: " Pietro Ceccarelli", team: "perpignan", positions: ["Pilier"], rarity: "rare", nat: "ITA" },
  { name: " Marco Riccioni", team: "perpignan", positions: ["Pilier"], rarity: "rare", nat: "ITA" },
  { name: "Mathys Lotrian", team: "perpignan", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Bastien Chinarro", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Jonny Gray", team: "perpignan", positions: ["Deuxième ligne"], rarity: "rare", nat: "ECO" },
  { name: "José Madeira", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "POR" },
  { name: "Davit Lagvilava", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "GEO" },
  { name: "Adrien Warion", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Noe Della Schiava", team: "perpignan", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mattéo Le Corvec", team: "perpignan", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Peceli Yato", team: "perpignan", positions: ["Troisième ligne"], rarity: "epique", nat: "FIJ" },
  { name: "Lucas Velarte", team: "perpignan", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "James Hall", team: "perpignan", positions: ["Demi de mêlée"], rarity: "commune", nat: "AFS" },
  { name: "Luke McGrath", team: "perpignan", positions: ["Demi de mêlée"], rarity: "epique", nat: "IRL" },
  { name: "Gabin Kretchmann", team: "perpignan", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Eneriko Buliruarua", team: "perpignan", positions: ["Centre", "Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Duncan Paia'Aua", team: "perpignan", positions: ["Centre"], rarity: "commune", nat: "SAM" },
  { name: "Job Poulet", team: "perpignan", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Braydon Eenor", team: "perpignan", positions: ["Centre"], rarity: "rare", nat: "NZL" },
  { name: "Sevu Reece", team: "perpignan", positions: ["Ailier"], rarity: "epique", nat: "NZL" },
  { name: "Maxim Granell", team: "perpignan", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Jefferson-Lee Joseph", team: "perpignan", positions: ["Ailier", "Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Setareki Toganiyadrava", team: "perpignan", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Théo Forner", team: "perpignan", positions: ["Ailier", "Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Tristan Tedder", team: "perpignan", positions: ["Demi d'ouverture","Arrière"], rarity: "commune", nat: "AFS" },

  // ----- AVIRON BAYONNAIS -----
  { name: "Manu Tuilagi", team: "bayonne", positions: ["Centre"], rarity: "epique", nat: "ANG" },
  { name: "Sireli Maqala", team: "bayonne", positions: ["Centre", "Ailier"], rarity: "epique", nat: "FIJ" },
  { name: "Joris Segonds", team: "bayonne", positions: ["Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Baptiste Chouzenoux", team: "bayonne", positions: ["Troisième ligne", "Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Arthur Iturria", team: "bayonne", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Guillaume Rouet", team: "bayonne", positions: ["Demi de mêlée"], rarity: "rare", nat: "ESP" },
  { name: "Facundo Bosch", team: "bayonne", positions: ["Talonneur"], rarity: "rare", nat: "ARG" },
  { name: "Tevita Tatafu", team: "bayonne", positions: ["Pilier"], rarity: "rare", nat: "TGA" },
  { name: "Rodrigo Bruni", team: "bayonne", positions: ["Troisième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Cheikh Tiberghien", team: "bayonne", positions: ["Arrière", "Centre"], rarity: "commune", nat: "FRA" },
  { name: "Mateo Carreras", team: "bayonne", positions: ["Ailier"], rarity: "commune", nat: "ARG" },
  { name: "Rémy Baget", team: "bayonne", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Federico Mori", team: "bayonne", positions: ["Centre", "Ailier"], rarity: "commune", nat: "ITA" },
  { name: "Guillaume Martocq", team: "bayonne", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Arnaud Erbinartegaray", team: "bayonne", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Maxime Machenaud", team: "racing92", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Lucas Paulos", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "ARG" },
  { name: "Denis Marchois", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Pierre Huguet", team: "bayonne", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Heguy", team: "bayonne", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Lucas Martin", team: "bayonne", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Swan Cormenier", team: "bayonne", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Luke Tagi", team: "bayonne", positions: ["Pilier"], rarity: "commune", nat: "FIJ" },
  { name: "Tom Spring", team: "bayonne", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Andy Bordelai", team: "bayonne", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Lasha Macharashvili", team: "bayonne", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Igniacio Calles", team: "bayonne", positions: ["Pilier"], rarity: "rare", nat: "ARG" },
  { name: "Ewan Johnson", team: "bayonne", positions: ["Deuxième ligne"], rarity: "rare", nat: "ECO" },	
  { name: "Esteban Capilla", team: "bayonne", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Giovanni Habel-Kuffner", team: "bayonne", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },	
  { name: "Rob Leota", team: "bayonne", positions: ["Troisième ligne"], rarity: "rare", nat: "AUS" },
  { name: "Alexandre Fischer", team: "bayonne", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },	
  { name: "Herschel Jantjies", team: "bayonne", positions: ["Demi de mêlée"], rarity: "rare", nat: "AFS" },
  { name: "Baptiste Germain", team: "clermont", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Léo Coly", team: "bayonne", positions: ["Demi de mêlée","Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Nadir Megdoud", team: "bayonne", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Yohan Orabé", team: "bayonne", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  
    // ----- RC VANNES (reprend les places de l'ex-US Montauban) -----
{ name: "Charles-Henri Berguet", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "BEL" },
{ name: "Wayan De Benedittis", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
{ name: "Simon Bourgeois", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
{ name: "Hugo Djehi", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
{ name: "Thomas Duchene", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
{ name: "Santiago Medrano", team: "vannes", positions: ["Pilier"], rarity: "rare", nat: "ARG" },
{ name: "Nick Schonert", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "AFS" },
{ name: "Théo Béziat", team: "vannes", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
{ name: "Cyril Blanchard", team: "vannes", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
{ name: "Dave Cherry", team: "vannes", positions: ["Talonneur"], rarity: "commune", nat: "ECO" },
{ name: "James O’Reilly", team: "vannes", positions: ["Talonneur"], rarity: "commune", nat: "NZL" },
{ name: "Mattéo Desjeux", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
{ name: "Thomas Geffré", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
{ name: "Eric Marks", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "ALL" },
{ name: "Fabrice Metz", team: "vannes", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
{ name: "Timothé Mézou", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
{ name: "Simon Augry", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
{ name: "Steeve Blanc-Mappaz", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
{ name: "Léon Boulier", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
{ name: "Joseph Edwards", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "NZL" },
{ name: "Francisco Gorrissen", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "ARG" },
{ name: "Edoardo Iachizzi", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "ITA" },
{ name: "Sione Kalamafoni", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "TGA" },
{ name: "Kitione Kamikamica", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "FIJ" },
{ name: "Juan-Bautista Pedemonte", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "ARG" },
{ name: "Mikheil Alania", team: "vannes", positions: ["Demi de mêlée"], rarity: "commune", nat: "GEO" },
{ name: "Michael Ruru", team: "vannes", positions: ["Demi de mêlée"], rarity: "rare", nat: "NZL" },
{ name: "Jules Le BAil", team: "vannes", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
{ name: "Richard Judd", team: "vannes", positions: ["Demi de mêlée"], rarity: "commune", nat: "NZL" },
{ name: "Maxime Lafage", team: "vannes", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
{ name: "Thibault Debaes", team: "vannes", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
{ name: "Jean Cotarmanac'h", team: "vannes", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
{ name: "Robin Taccola", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FRA" },
{ name: "Eliott Roudil", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FRA" },
{ name: "Iñaki Ayarza", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "CHI" },
{ name: "Pierre Boudehent", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FRA" },
{ name: "Marin Boulier", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FRA" },
{ name: "Francis Saili", team: "vannes", positions: ["Centre", "Ailier"], rarity: "rare", nat: "NZL" },
{ name: "Enzo Benmegal", team: "vannes", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
{ name: "Romaric Camou", team: "vannes", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
{ name: "Ben Stevenson", team: "vannes", positions: ["Ailier"], rarity: "commune", nat: "ANG" },
{ name: "Paul Surano", team: "vannes", positions: ["Arrière"], rarity: "epique", nat: "FRA" },
{ name: "Gwenaël Duplenne", team: "vannes", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
{ name: "Anthony Bouthier", team: "vannes", positions: ["Arrière"], rarity: "epique", nat: "FRA" },

  // ----- MONTPELLIER -----
  { name: "Nika Abuladze", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "GEO" },
  { name: "Mohamed Haouas", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Wilfrid Hounkpatin", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "SEN" },
  { name: "Valentin Welsch", team: "montpellier", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Reda Wardi", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Baptiste Erdocio", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Luka Japaridze", team: "montpellier", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Christopher Tolofua", team: "montpellier", positions: ["Talonneur", "Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Lyam Akrab", team: "montpellier", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Ricky Riccitelli", team: "montpellier", positions: ["Talonneur"], rarity: "commune", nat: "AFS" },
  { name: "Jordan Uelese", team: "montpellier", positions: ["Talonneur"], rarity: "rare", nat: "AUS" },
  { name: "Tyler Duguid", team: "montpellier", positions: ["Deuxième ligne"], rarity: "commune", nat: "CAN" },
  { name: "Matthieu Uhila", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Adam Beard", team: "montpellier", positions: ["Deuxième ligne"], rarity: "commune", nat: "PDG" },
  { name: "Bastien Chalureau", team: "montpellier", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Florian Verhaeghe", team: "montpellier", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Yacouba Camara", team: "montpellier", positions: ["Troisième ligne", "Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Mahamadou Diaby", team: "montpellier", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Billy Vunipola", team: "montpellier", positions: ["Troisième ligne"], rarity: "epique", nat: "ANG" },
  { name: "Langi Gleeson", team: "montpellier", positions: ["Troisième ligne"], rarity: "commune", nat: "AUS" },
  { name: "Alexander Masibaka", team: "montpellier", positions: ["Troisième ligne"], rarity: "commune", nat: "AUS" },
  { name: "Lenni Nouchi", team: "montpellier", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Alexandre Bécognée", team: "montpellier", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Marco Tauleigne", team: "montpellier", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ali Price", team: "montpellier", positions: ["Demi de mêlée"], rarity: "rare", nat: "ECO" },
  { name: "Alexis Bernadet", team: "montpellier", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Vincent", team: "montpellier", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Domingo Miotti", team: "montpellier", positions: ["Demi d'ouverture"], rarity: "commune", nat: "ARG" },
  { name: "Lennox Anyanwu", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "ANG" },
  { name: "Arthur Vincent", team: "montpellier", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Justo Piccardo", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "ARG" },
  { name: "Thomas Darmon", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Auguste Cadot", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Karl Martin", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Donovan Taofifenua", team: "montpellier", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Maël Moustin", team: "montpellier", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Gabriel Ngandebe", team: "montpellier", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Stuart Hogg", team: "montpellier", positions: ["Arrière", "Demi d'ouverture"], rarity: "epique", nat: "ECO" },
  { name: "Jon Echegaray", team: "montpellier", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Tom Banks", team: "montpellier", positions: ["Arrière"], rarity: "commune", nat: "AUS" },

  // ----- RC TOULON -----
  { name: "Dany Priso", team: "toulon", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Emerick Setiano", team: "toulon", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Beka Gigashvili", team: "toulon", positions: ["Pilier"], rarity: "rare", nat: "GEO" },
  { name: "Jean-Baptiste Gros", team: "toulon", positions: ["Pilier"], rarity: "epique", nat: "FRA" },
  { name: "Kyle Sinckler", team: "toulon", positions: ["Pilier"], rarity: "rare", nat: "ANG" },
  { name: "Teddy Baubigny", team: "toulon", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Gianmarco Lucchesi", team: "toulon", positions: ["Talonneur"], rarity: "rare", nat: "ITA" },
  { name: "Pierre Damond", team: "toulon", positions: ["Talonneur"], rarity: "commune", nat: "FRA" } ,
  { name: "David Ribbans", team: "toulon", positions: ["Deuxième ligne"], rarity: "epique", nat: "ANG" },
  { name: "Giorgi Javakhia", team: "toulon", positions: ["Deuxième ligne"], rarity: "commune", nat: "GEO" },	
  { name: "Corentin Mezou", team: "toulon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Junior Kpoku", team: "toulon", positions: ["Deuxième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Brian Alainu'uese", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "SAM" },
  { name: "Judicaël Cancoriet", team: "toulon", positions: ["Troisième ligne","Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Swan Rebbadj", team: "toulon", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Matthias Halagahu", team: "toulon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Charles Ollivon", team: "toulon", positions: ["Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Jules Coulon", team: "toulon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Joe Quere-Karaba", team: "toulon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Patrick Tuifua", team: "toulon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Zach Mercer", team: "toulon", positions: ["Troisième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Beka Shvangiradze", team: "lyon", positions: ["Troisième ligne"], rarity: "rare", nat: "GEO" },
  { name: "Esteban Abadie", team: "toulon", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Lewis Ludlam", team: "toulon", positions: ["Troisième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Baptiste Serin", team: "toulon", positions: ["Demi de mêlée"], rarity: "epique", nat: "FRA" },
  { name: "Ben White", team: "toulon", positions: ["Demi de mêlée"], rarity: "rare", nat: "ECO" },
  { name: "Jules Danglot", team: "toulon", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Clovis Le Bail", team: "toulon", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Tomas Albornoz", team: "toulon", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ARG" },
  { name: "Matéo Garcia", team: "toulon", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Paolo Garbisi", team: "toulon", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ITA" },
  { name: "Gaël Fickou", team: "toulon", positions: ["Centre"], rarity: "epique", nat: "FRA" },
  { name: "Antoine Frisch", team: "toulon", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Juan Ignacio Brex", team: "toulon", positions: ["Centre"], rarity: "rare", nat: "ITA" },
  { name: "Oliver Cowie", team: "toulon", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Ma'a Nonu", team: "toulon", positions: ["Centre"], rarity: "legendaire", nat: "NZL" },
  { name: "Mathieu Smaïli", team: "toulon", positions: ["Centre","Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Rayan Rebbadj", team: "toulon", positions: ["Centre","Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Gabbin Villière", team: "toulon", positions: ["Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Setariki Tuicuvu", team: "toulon", positions: ["Ailier", "Arrière"], rarity: "commune", nat: "FIJ" },
  { name: "Melvyn Jaminet", team: "toulon", positions: ["Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Marius Domon", team: "toulon", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Gael Dréan", team: "toulon", positions: ["Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Mathis Ferté", team: "toulon", positions: ["Arrière","Ailier"], rarity: "commune", nat: "FRA" },

  // ----- STADE ROCHELAIS -----
  { name: "Louis Penverne", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Joel Sclavi", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "ARG" },
  { name: "Alexandre Kaddouri", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Aleksandre Kuntelia", team: "lapelle", positions: ["Pilier"], rarity: "rare", nat: "GEO" },
  { name: "Karl Sorin", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Pierre Bourgarit", team: "lapelle", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Quentin Lespiaucq", team: "lapelle", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Tolu Latu", team: "lapelle", positions: ["Talonneur"], rarity: "rare", nat: "AUS" },
  { name: "Nikolozi Sutidze", team: "lapelle", positions: ["Talonneur"], rarity: "commune", nat: "GEO" },
  { name: "Kane Douglas", team: "lapelle", positions: ["Deuxième ligne"], rarity: "rare", nat: "AUS" },
  { name: "Watisoni Waqanisaravi", team: "lapelle", positions: ["Deuxième ligne","Troisième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Will Skelton", team: "lapelle", positions: ["Deuxième ligne"], rarity: "epique", nat: "AUS" },
  { name: "Salmaan Moerat", team: "lapelle", positions: ["Deuxième ligne"], rarity: "rare", nat: "AFS" },
  { name: "Thomas Lavault", team: "lapelle", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ultan Dillane", team: "lapelle", positions: ["Deuxième ligne"], rarity: "commune", nat: "IRL" },
  { name: "Paul Boudehent", team: "lapelle", positions: ["Troisième ligne","Deuxième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Grégory Alldritt", team: "lapelle", positions: ["Troisième ligne"], rarity: "international", nat: "FRA" },
  { name: "Théo Mcfarland", team: "lapelle", positions: ["Troisième ligne"], rarity: "rare", nat: "SAM" },
  { name: "Andy Timo", team: "lapelle", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Matthias Haddad", team: "lapelle", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Oscar Jegou", team: "lapelle", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Nolann Le Garrec", team: "lapelle", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Thomas Berjon", team: "lapelle", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Lucas Zamorano", team: "lapelle", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Antoine Hastoy", team: "lapelle", positions: ["Demi d'ouverture","Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Ben Healy", team: "lapelle", positions: ["Demi d'ouverture"], rarity: "rare", nat: "IRL" },
  { name: "Simeli Daunivucu", team: "lapelle", positions: ["Centre","Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Adrien Seguret", team: "lapelle", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "David Kriel", team: "lapelle", positions: ["Centre"], rarity: "rare", nat: "AFS" },
  { name: "Semi Lagivala", team: "lapelle", positions: ["Centre","Ailier"], rarity: "rare", nat: "FIJ" },
  { name: "Levani Botia", team: "lapelle", positions: ["Centre","Troisième ligne"], rarity: "epique", nat: "FIJ" },
  { name: "Jonathan Danty", team: "lapelle", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Ulupano Seuteni", team: "lapelle", positions: ["Centre"], rarity: "commune", nat: "SAM" },
  { name: "Jules Favre", team: "lapelle", positions: ["Centre","Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Jack Nowell", team: "lapelle", positions: ["Ailier","Centre"], rarity: "commune", nat: "ANG" },
  { name: "Nathan Bollengier", team: "lapelle", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Hoani Bosmorin", team: "lapelle", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Suliasi Vunivalu", team: "lapelle", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Ugo Pacome", team: "lapelle", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Dillyn Leyds", team: "lapelle", positions: ["Arrière","Ailier"], rarity: "epique", nat: "AFS" },
  { name: "Davit Niniashvili", team: "lapelle", positions: ["Arrière","Ailier"], rarity: "epique", nat: "GEO" },

  // ----- COURSE 92 -----
  {  nom : "Eddy Ben Arous" , équipe : "racing92" , positions : [ "Pilier" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Guram Gogichashvili" , équipe : "racing92" , positions : [ "Pilier" ] , rareté : "commune" , nat : "GEO"  } ,
  {  nom : "Hassane Kolingar" , équipe : "racing92" , positions : [ "Pilier" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Gia Nurashvili" , équipe : "racing92" , positions : [ "Pilier" ] , rareté : "commune" , nat : "GEO"  } ,
  {  nom : "Lasha Kharaishvili" , équipe : "racing92" , positions : [ "Pilier" ] , rareté : "commune" , nat : "GEO"  } ,
  {  nom : "Janick Tarit" , équipe : "racing92" , positions : [ "Talonneur" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Demba Bamba" , équipe : "racing92" , positions : [ "Pilier" ] , rareté : "rare" , nat : "FRA"  } ,
  {  nom : "Taniela Tupou" , équipe : "racing92" , positions : [ "Pilier" ] , rareté : "epique" , ​​nat : "AUS"  } ,
  {  nom : "Diego Escobar" , équipe : "racing92" , positions : [ "Talonneur" ] , rareté : "commune" , nat : "CHI"  } ,
  {  nom : "Feleti Kaitu'u" , équipe : "racing92" , positions : [ "Talonneur" ] , rareté : "commune" , nat : "AUS"  } ,
  {  nom : "Robin Couly" , équipe : "racing92" , positions : [ "Talonneur" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Will Rowlands" , équipe : "racing92" , positions : [ "Deuxième ligne" ] , rareté : "rare" , nat : "PDG"  } ,
  {  nom : "Baptiste Chouzenoux" , équipe : "racing92" , positions : [ "Deuxième ligne" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Fabien Sanconnie" , équipe : "racing92" , positions : [ "Deuxième ligne" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Junior Fisi'Ihoi" , équipe : "racing92" , positions : [ "Deuxième ligne" ] , rareté : "commune" , nat : "NZL"  } ,
  {  nom : "Romain Taofifenua" , équipe : "racing92" , positions : [ "Deuxième ligne" ] , rareté : "rare" , nat : "FRA"  } ,
  {  nom : "Jonathan Hill" , équipe : "racing92" , positions : [ "Deuxième ligne" , "Troisième ligne" ] , rareté : "rare" , nat : "ANG"  } ,
  {  nom : "Nathan Hughes" , équipe : "racing92" , positions : [ "Troisième ligne" , "Deuxième ligne" ] , rareté : "rare" , nat : "FIJ"  } ,
  {  nom : "Thomas Lainault" , équipe : "racing92" , positions : [ "Deuxième ligne" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Soumaila Camara" , équipe : "racing92" , positions : [ "Troisième ligne" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Shingi Manyarara" , équipe : "racing92" , positions : [ "Trosième ligne" ] , rareté : "commune" , nat : "ZIM"  } ,
  {  nom : "Lekima Tagitagivalu" , équipe : "racing92" , positions : [ "Deuxième ligne" , "Trosième ligne" ] , rareté : "commune" , nat : "FIJ"  } ,
  {  nom : "Jordan Joseph" , équipe : "racing92" , positions : [ "Troisième ligne" ] , rareté : "rare" , nat : "FRA"  } ,
  {  nom : "Maxime Baudonne" , équipe : "racing92" , positions : [ "Troisième ligne" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Ibrahim Diallo" , équipe : "racing92" , positions : [ "Troisième ligne" ] , rareté : "commune" , nat : "FRA"  } ,
  {  nom : "Léo Carbonneau" , équipe : "racing92" , positions : [ "Demi de mêlée" ] , rareté : "rare" , nat : "FRA"  } ,
  { name: "Kleo Labarbe", team: "racing92", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Ugo Seunes", team: "racing92", positions: ["Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Geronimo Prisciantelli", team: "racing92", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ARG" },
  { name: "Antoine Gibert", team: "racing92", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Sam James", team: "racing92", positions: ["Centre","Arière"], rarity: "commune", nat: "ANG" },
  { name: "Josua Tuisova", team: "racing92", positions: ["Centre","Ailier"], rarity: "epique", nat: "FIJ" },
  { name: "Joseph Manu", team: "racing92", positions: ["Centre"], rarity: "commune", nat: "AUS" },
  { name: "Wilfried Hulleu", team: "racing92", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Wame Naituvi", team: "racing92", positions: ["Centre","Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Selestino Ravutaumada", team: "racing92", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Vinaya Habosi", team: "racing92", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Max Spring", team: "racing92", positions: ["Arrière"], rarity: "rare", nat: "FRA" },

  // ----- LYON OU -----
  { name: "Thomas Moukoro", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Camille Chat", team: "lyon", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Baptiste Couilloud", team: "lyon", positions: ["Demi de mêlée"], rarity: "epique", nat: "FRA" },
  { name: "Jiuta Wainiqolo", team: "lyon", positions: ["Ailier"], rarity: "rare", nat: "FIJ" },
  { name: "Leo Berdeu", team: "lyon", positions: ["Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Beka Saginadze", team: "lyon", positions: ["Troisième ligne"], rarity: "rare", nat: "GEO" },
  { name: "Dylan Cretin", team: "lyon", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Killian Geraci", team: "bayonne", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Guillaume Marchand", team: "lyon", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Jérôme Rey", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Felix Lambey", team: "lyon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mickaël Guillard", team: "lyon", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Arno Botha", team: "lyon", positions: ["Troisième ligne"], rarity: "commune", nat: "AFS" },
  { name: "Maxime Gouzou", team: "lyon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Théo William", team: "lyon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Paddy Jackson", team: "lyon", positions: ["Demi d'ouverture"], rarity: "commune", nat: "IRL" },
  { name: "Alfred Parisien", team: "lyon", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Thibaut Regard", team: "lyon", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Ethan Dumortier", team: "lyon", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Alexandre Tchaptchet", team: "lyon", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Jermaine Ainsley", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "NZL" },
  { name: "Irakli Aptsiauri", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Cedate Gomes Sa", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Hamza Kaabeche", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Mathis Sarragallet", team: "lyon", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },	
  { name: "Liam Allen", team: "lyon", positions: ["Troisième ligne"], rarity: "commune", nat: "NZL" },
  { name: "Marvin Okuya", team: "lyon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Sam Simmonds", team: "lyon", positions: ["Trosième ligne"], rarity: "rare", nat: "ANG" },	
  { name: "Esteban Gonzalez", team: "lyon", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Charlie Cassang", team: "lyon", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Martin Méliande", team: "lyon", positions: ["Demi d'ouverture","Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Iosefo Masi", team: "lyon", positions: ["Centre"], rarity: "commune", nat: "FIJ" },	
  { name: "Josiah Maraku", team: "lyon", positions: ["Centre"], rarity: "rare", nat: "NZL" },
  { name: "Theo Millet", team: "lyon", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Monty Ioane", team: "lyon", positions: ["Ailier"], rarity: "rare", nat: "ITA" },
  { name: "Arthur Mathiron", team: "lyon", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Gabin Lorre", team: "lyon", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Gallo", team: "lyon", positions: ["Pilier"], rarity: "rare", nat: "ARG" },
  { name: "Tim Hoyt", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "ANG" },
  { name: "Sanele Nohamba", team: "lyon", positions: ["Demi de mêlée"], rarity: "commune", nat: "AFS" },

  // ----- ASM CLERMONT -----
  { name: "Baptiste Jauneau", team: "clermont", positions: ["Demi de mêlée"], rarity: "epique", nat: "FRA" },
  { name: "Harry Plummer", team: "clermont", positions: ["Demi d'ouverture"], rarity: "epique", nat: "NZL" },
  { name: "Alivereti Raka", team: "clermont", positions: ["Ailier"], rarity: "epique", nat: "FRA" },
  { name: "Marcos Kremer", team: "clermont", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Léon Darricarrère", team: "clermont", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Sébastien Bézy", team: "montpellier", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Peceli Yato", team: "perpignan", positions: ["Troisième ligne", "Deuxième ligne"], rarity: "rare", nat: "FIJ" },
  { name: "George Moala", team: "clermont", positions: ["Centre"], rarity: "rare", nat: "TGA" },
  { name: "Étienne Falgoux", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Joris Jurand", team: "clermont", positions: ["Ailier", "Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Thibaud Lanen", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Selevasio Tolofua", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Oskar Rixen", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "ALL" },
  { name: "Cristian Ojovan", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "MDA" },
  { name: "Régis Montagne", team: "clermont", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Giorgi Akhaladze", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Barnabé Massa", team: "clermont", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Rob Simmons", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "AUS" },
  { name: "Killian Tixeront", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Lucas Dessaigne", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Bautista Delguy", team: "clermont", positions: ["Ailier"], rarity: "rare", nat: "ARG" },
  { name: "Irae Simone", team: "clermont", positions: ["Centre"], rarity: "commune", nat: "AUS" },
  { name: "Kylan Hamdaoui", team: "clermont", positions: ["Arrière", "Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Giorgi Dzmanashvili", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Matheo Frisach", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Sacha Lotrian", team: "clermont", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Giga Tutisani", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Etienne Fourcade", team: "clermont", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Ceyte", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Léo Michaux", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Tevita Ratuva", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Anthime Hemery", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Pio Muarua", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Pita-Gus Sowakula", team: "clermont", positions: ["Troisième ligne"], rarity: "rare", nat: "NZL" },
  { name: "Baptiste Veschambre", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Lucas Zamora", team: "clermont", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Timeo Frier", team: "clermont", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Alivereti Loaloa", team: "clermont", positions: ["Centre"], rarity: "commune", nat: "FIJ" },
  { name: "Yerim Fall", team: "clermont", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Axel Guillaud", team: "clermont", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Etene Nanai-Seturo", team: "clermont", positions: ["Arrière"], rarity: "rare", nat: "NZL" },

  
  // ----- SECTION PALOISE -----
  { name: "Thomas Laclayat", team: "pau", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Guram Papidze", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Lesko Kaulashvili", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Hugo Parrou", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Daniel Bibi-Bizewu", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Sébastien Senca", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Siate Tokolahi", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "TGA" },
  { name: "Jon Zabala", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "ESP" },
  { name: "Lucas Rey", team: "pau", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Romain Delhommel", team: "pau", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Julian Montoya", team: "pau", positions: ["Talonneur"], rarity: "rare", nat: "ARG" },
  { name: "Jimi Maximin", team: "pau", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Hugo Auradou", team: "pau", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Mickael Capelli", team: "pau", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Jolmes", team: "pau", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Facundo Isa", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Beka Gorgadze", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "GEO" },
  { name: "Reece Hewat", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "AUS" },
  { name: "Sacha Zegueur", team: "pau", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Loïc Credoz", team: "pau", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Luke Whitelock", team: "pau", positions: ["Troisième ligne"], rarity: "legendaire", nat: "NZL" },
  { name: "Thibault Daubagna", team: "pau", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Thomas Souverbie", team: "pau", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Joe Simmonds", team: "pau", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ANG" },
  { name: "Axel Desperes", team: "pau", positions: ["Demi d'ouverture", "Centre"], rarity: "commune", nat: "FRA" },
  { name: "Clément Mondinat", team: "pau", positions: ["Demi d'ouverture", "Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Émilien Gailleton", team: "pau", positions: ["Centre"], rarity: "epique", nat: "FRA" },
  { name: "Fabien Brau-Boirie", team: "pau", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Nathan Decron", team: "pau", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Tumua Manu", team: "pau", positions: ["Centre"], rarity: "commune", nat: "SAM" },
  { name: "Clément Valentino", team: "pau", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Clement Laporte", team: "pau", positions: ["Ailier", "Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Aaron Grandidier", team: "pau", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Carol", team: "pau", positions: ["Ailier", "Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Théo Attissogbe", team: "pau", positions: ["Ailier", "Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Grégoire Arfeuil", team: "pau", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Aymeric Luc", team: "pau", positions: ["Arrière", "Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Jack Maddocks", team: "pau", positions: ["Arrière"], rarity: "rare", nat: "AUS" },
  { name: "Gonzalo Garcia", team: "pau", positions: ["Demi de mêlée"], rarity: "commune", nat: "ARG" },
  { name: "Rodrigo Marta", team: "pau", positions: ["Ailier"], rarity: "commune", nat: "POR" },

  // ----- CASTRES OLYMPIQUE -----
  { name: "Louis Le Brun", team: "castres", positions: ["Demi d'ouverture", "Centre"], rarity: "rare", nat: "FRA" },
  { name: "Tyler Ardron", team: "castres", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "epique", nat: "CAN" },
  { name: "Santiago Arata", team: "castres", positions: ["Demi de mêlée"], rarity: "epique", nat: "URU" },
  { name: "Tom Staniforth", team: "castres", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Mathieu Babillot", team: "castres", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Pierre Colonna", team: "castres", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Levan Chilachava", team: "castres", positions: ["Pilier"], rarity: "rare", nat: "GEO" },
  { name: "Vilimoni Botitu", team: "castres", positions: ["Centre", "Demi d'ouverture"], rarity: "rare", nat: "FIJ" },
  { name: "Geoffrey Palis", team: "castres", positions: ["Arrière", "Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Nathanaël Hulleu", team: "vannes", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Rémy Baget", team: "castres", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Adrea Cocagi", team: "castres", positions: ["Centre"], rarity: "commune", nat: "FIJ" },
  { name: "Jack Goodhue", team: "castres", positions: ["Centre"], rarity: "epique", nat: "NZL" },
  { name: "Pierre Popelin", team: "vannes", positions: ["Demi d'ouverture", "Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Gauthier Doubrère", team: "castres", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Jeremy Fernandez", team: "castres", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Abraham Papali'i", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "NZL" },
  { name: "Baptiste Cope", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Florent Vanverberghe", team: "castres", positions: ["Deuxième ligne", "Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Will Collier", team: "castres", positions: ["Pilier"], rarity: "commune", nat: "ANG" },
  { name: "Quentin Walcker", team: "castres", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Loris Zarantonello", team: "castres", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Lois Guerois-Galisson", team: "castres", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Nicolas Corato", team: "castres", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Teddy Durand", team: "castres", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Paul Jedrasiak", team: "castres", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Gauthier Maravat", team: "castres", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Guillaume Ducat", team: "castres", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Delaporte", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Feibyan Tukino", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Simon Meka", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Veresa Ramototabua", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Enzo Hervé", team: "castres", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Atu Manu", team: "castres", positions: ["Centre"], rarity: "rare", nat: "FIJ" },
  { name: "Adam Vargas", team: "castres", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Christian Ambadiang", team: "castres", positions: ["Ailier"], rarity: "rare", nat: "CAM" },
  { name: "Vuate Karawalevu ", team: "castres", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Théo Chabouni", team: "castres", positions: ["Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Dalton Papali'i", team: "castres", positions: ["Troisième ligne"], rarity: "epique", nat: "NZL" },

  // ----- STADE FRANÇAIS -----
  { name: "Paul Alo-Emile", team: "stadefr", positions: ["Pilier"], rarity: "rare", nat: "SAM" },
  { name: "Giacomo Nicotera", team: "stadefr", positions: ["Talonneur"], rarity: "rare", nat: "ITA" },
  { name: "Lucas Peyresblanques", team: "stadefr", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Paul Gabrillagues", team: "stadefr", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Baptiste Pesenti", team: "pau", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Sekou Macalou", team: "stadefr", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Yoan Tanga", team: "stadefr", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Romain Briatte", team: "stadefr", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Tanginoa Halaifonua", team: "stadefr", positions: ["Troisième ligne"], rarity: "rare", nat: "TGA" },
  { name: "Louis Carbonel", team: "stadefr", positions: ["Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Léo Barré", team: "stadefr", positions: ["Demi d'ouverture", "Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Jeremy Ward", team: "stadefr", positions: ["Centre"], rarity: "rare", nat: "AFS" },
  { name: "Joe Marchant", team: "stadefr", positions: ["Centre", "Ailier"], rarity: "rare", nat: "ANG" },
  { name: "Lester Etien", team: "stadefr", positions: ["Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Peniasi Dakuwaqa", team: "stadefr", positions: ["Ailier"], rarity: "rare", nat: "FIJ" },
  { name: "Sergo Abramishvili", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Moses Alo-Emile", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "SAM" },
  { name: "Giorgi Melikidze", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Jack Iscaro", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "USA" },
  { name: "Isaac Koffi", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Alvaro Garcia", team: "stadefr", positions: ["Talonneur"], rarity: "commune", nat: "ESP" },
  { name: "Pierre-Henri Azagoh", team: "stadefr", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mathieu Hirigoyen", team: "stadefr", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ryan Chapuis", team: "stadefr", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Iakopo Mapu", team: "stadefr", positions: ["Troisième ligne"], rarity: "commune", nat: "SAM" },
  { name: "Juan Martin Scelzo", team: "stadefr", positions: ["Troisième ligne"], rarity: "commune", nat: "ARG" },
  { name: "Paul Abadie", team: "stadefr", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Tawera Kerr-Barlow", team: "stadefr", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Thibaut Motassi", team: "stadefr", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Martin Blum", team: "stadefr", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Louis Foursans", team: "stadefr", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Ihaia West", team: "stadefr", positions: ["Demi d'ouverture"], rarity: "commune", nat: "NZL" },
  { name: "Julien Delbouis", team: "stadefr", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Noah Nene", team: "stadefr", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Tani Vili", team: "stadefr", positions: ["Centre","Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Samuel Ezeala", team: "stadefr", positions: ["Ailier", "Centre"], rarity: "commune", nat: "ESP" },
  { name: "Mathis Ibo", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Joe Jonas", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "AFS" },
  { name: "Yannick Lodjro", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Charles Laloi", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Léo Monin", team: "stadefr", positions: ["Arrière"], rarity: "commune", nat: "AUS" },
  { name: "Thierry Paiva", team: "stadefr", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Jacques Botha", team: "stadefr", positions: ["Deuxième ligne"], rarity: "commune", nat: "AFS" },
  { name: "Setareki Turagacoke", team: "stadefr", positions: ["Deuxième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Rufus Mclean", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "USA" },
  { name: "Tomasi Maka", team: "stadefr", positions: ["Talonneur"], rarity: "commune", nat: "NZL" },
  
    
];

// Configuration des raretés (couleur + probabilité de base)

const LEGENDS = [
  { name: "Uini Atonio", team: "lapelle", clubs: ["lapelle"], positions: ["Pilier"], rarity: "legendaire", nat: "FRA" },
  { name: "Sébastien Chabal", team: "racing92", clubs: ["bourgoinjallieu", "racing92"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Thierry Dusautoir", team: "toulouse", clubs: ["toulouse"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Imanol Harinordoquy", team: "biarritz", clubs: ["biarritz", "toulouse"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Dimitri Yachvili", team: "biarritz", clubs: ["biarritz"], positions: ["Demi de mêlée"], rarity: "legendaire", nat: "FRA" },
  { name: "Johnny Wilkinson", team: "toulon", clubs: ["toulon"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "ANG" },
  { name: "Frédéric Michalak", team: "toulouse", clubs: ["toulouse", "toulon", "lyon"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "FRA" },
  { name: "Yannick Jauzion", team: "toulouse", clubs: ["toulouse"], positions: ["Centre"], rarity: "legendaire", nat: "FRA" },
  { name: "Mathieu Bastareaud", team: "toulon", clubs: ["stadefr", "toulon", "lyon"], positions: ["Centre"], rarity: "legendaire", nat: "FRA" },
  { name: "Virimi Vakatawa", team: "racing92", clubs: ["racing92"], positions: ["Centre"], rarity: "legendaire", nat: "FIJ" },
  { name: "Vincent Clerc", team: "toulouse", clubs: ["toulouse"], positions: ["Ailier"], rarity: "legendaire", nat: "FRA" },
  { name: "Maxime Médard", team: "toulouse", clubs: ["toulouse"], positions: ["Arrière"], rarity: "legendaire", nat: "FRA" },
  { name: "Brice Dulin", team: "lapelle", clubs: ["castres", "racing92", "lapelle"], positions: ["Arrière"], rarity: "legendaire", nat: "FRA" },
  { name: "Nans Ducuing", team: "ubb", clubs: ["ubb"], positions: ["Arrière", "Ailier"], rarity: "legendaire", nat: "FRA" },
  { name: "Owen Farrell", team: "racing92", clubs: ["racing92"], positions: ["Demi d'ouverture", "Centre"], rarity: "legendaire", nat: "ANG" },
  { name: "Siya Kolisi", team: "racing92", clubs: ["racing92"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "AFS" },
  { name: "Pita Ahki", team: "toulouse", clubs: ["toulouse"], positions: ["Centre"], rarity: "legendaire", nat: "NZL" },
  { name: "Camille Lopez", team: "bayonne", clubs:["clermont","bayonne"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "FRA" },
  { name: "Dan Carter", team: "racing92", clubs:["perpignan","racing92"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "NZL" },
  { name: "Christophe Dominici", team: "stadefr", clubs:["stadefr"], positions: ["Ailier","Arrière"], rarity: "legendaire", nat: "FRA" },
  { name: "Sylvain Marconnet", team: "stadefr", clubs:["stadefr"], positions: ["Pilier"], rarity: "legendaire", nat: "FRA" },
  { name: "Nicolas Mas", team: "perpignan", clubs:["perpignan"], positions: ["Pilier"], rarity: "legendaire", nat: "FRA" },
  { name: "Percy Montgomery", team: "perpignan", clubs:["perpignan"], positions: ["Arrière"], rarity: "legendaire", nat: "AFS" },
  { name: "Bryan Habana", team: "toulon", clubs:["toulon"], positions: ["Ailier"], rarity: "legendaire", nat: "AFS" },
  { name: "Conrad Smith", team: "pau", clubs:["pau"], positions: ["Centre"], rarity: "legendaire", nat: "NZL" },
  { name: "Sergio Parisse", team: "stadefr", clubs:["stadefr","toulon"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "ITA" },
  { name: "Brock James", team: "clermont", clubs:["clermont"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "AUS" },

	
];

PLAYERS.push(...LEGENDS);

const RARITIES = {
  commune:    { label: "Commune",    color: "#9e9e9e", weight: 60, sellValue: 5 },
  rare:       { label: "Rare",       color: "#05DF72", weight: 27, sellValue: 10 },
  epique:     { label: "Épique",     color: "#9c27b0", weight: 10, sellValue: 25 },
  legendaire: { label: "Légende",    color: "#ffd700", weight: 0,  sellValue: 150 },
  international: { label: "International", color: "#1a1a2e", weight: 3, sellValue: 60 }
};

const PACKS = [
  {
    id: "standard",
    name: "Pack Nationale",
    description: "5 cartes — chances équilibrées",
    cardsCount: 5,
    cost: 100,
    weightModifier: { commune: 1, rare: 1, epique: 1, international: 1, legendaire: 0 }
  },
  {
    id: "premium",
    name: "Pack Pro D2",
    description: "5 cartes — meilleures chances de Rare+",
    cardsCount: 5,
    cost: 250,
    weightModifier: { commune: 0.4, rare: 1.5, epique: 1.8, international: 1.5, legendaire: 0 }
  },
  {
    id: "legendaire",
    name: "Pack TOP 14",
    description: "3 cartes — au moins une Épique garantie",
    cardsCount: 3,
    cost: 500,
    guaranteedRarity: "epique",
    weightModifier: { commune: 0.1, rare: 1, epique: 2.5, international: 3, legendaire: 0 }
  },
  {
    id: "international",
    name: "Pack International",
    description: "1 carte — un joueur Légende garanti",
    cardsCount: 1,
    cost: 1000,
    forcedRarity: "legendaire"
  },
  {
    id: "xv_demarrage",
    name: "Pack XV Démarrage",
    description: "15 cartes de départ — GRATUIT — 1 seule fois",
    cardsCount: 15,
    cost: 0,
    oneTime: true,
    locked: true
  },
  {
    id: "coup_envoi",
    name: "Pack Coup d'Envoi",
    description: "Disponible 1 fois par jour — GRATUIT",
    cardsCount: 1,   // 1 carte + 1 bonus RUGBIZ (géré séparément)
    cost: 0,
    daily: true,
    locked: true     // carte non revendable
  }
];
