// =========================================================
// RUGBIX — BASE DE DONNÉES
// Fichier exporté automatiquement depuis le panneau Admin
// Généré le : 01/09/2026 23:11:14
// Contient tous les ajouts, suppressions, modifications et notes
// personnalisées effectués depuis le jeu.
// =========================================================

const TEAMS = {
  "toulouse": { name: "Stade Toulousain", color: "#cc0000" },
  "ubb": { name: "Union Bordeaux-Bègles", color: "#73354C" },
  "racing92": { name: "Racing 92", color: "#add7f3" },
  "lapelle": { name: "Stade Rochelais", color: "#FFD000" },
  "toulon": { name: "RC Toulon", color: "#BA0B12" },
  "clermont": { name: "ASM Clermont Auvergne", color: "#FEEB2F" },
  "bayonne": { name: "Aviron Bayonnais", color: "#7AB7E7" },
  "pau": { name: "Section Paloise", color: "#007333" },
  "lyon": { name: "Lyon OU", color: "#C9424A" },
  "castres": { name: "Castres Olympique", color: "#A4B4CA" },
  "montpellier": { name: "Montpellier Hérault Rugby", color: "#002958" },
  "stadefr": { name: "Stade Français Paris", color: "#EC5E9D" },
  "perpignan": { name: "USA Perpignan", color: "#db1d3a" },
  "montauban": { name: "US Montauban", color: "#1A4934" },
  "biarritz": { name: "Biarritz Olympique", color: "#F20000" },
  "vannes": { name: "Rugby Club Vannes", color: "#001438" },
  "bourgoinjallieu": { name: "CS Bourgoin-Jallieu", color: "#003366" },
};

let PLAYERS = [
  { name: "Cyril Baille", team: "toulouse", positions: ["Pilier"], rarity: "epique", nat: "FRA" },
  { name: "Dorian Aldegheri", team: "toulouse", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Georges-Henri Colombe", team: "toulouse", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Benjamin Bertrand", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Rodrigue Neti", team: "toulouse", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Tom Rapetti", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "ARG" },
  { name: "David Ainu'u", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "USA" },
  { name: "Paul Mallez", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Joel Merkler", team: "toulouse", positions: ["Pilier","Deuxième ligne"], rarity: "commune", nat: "ESP" },
  { name: "Malachi Hawkes", team: "toulouse", positions: ["Pilier","Talonneur"], rarity: "commune", nat: "AUS" },
  { name: "Julien Marchand", team: "toulouse", positions: ["Talonneur"], rarity: "epique", nat: "FRA" },
  { name: "Peato Mauvaka", team: "toulouse", positions: ["Talonneur","Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Thomas Lacombre", team: "toulouse", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Thibaud Flament", team: "toulouse", positions: ["Deuxième ligne","Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Emmanuel Meafou", team: "toulouse", positions: ["Deuxième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Elias Efrain", team: "toulouse", positions: ["Deuxième ligne","Troisième ligne"], rarity: "commune", nat: "ARG" },
  { name: "Joshua Brennan", team: "toulouse", positions: ["Deuxième ligne","Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Clément Vergé", team: "toulouse", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Alexandre Roumat", team: "toulouse", positions: ["Troisième ligne","Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Romeo Bonnard Martin", team: "toulouse", positions: ["Troisième ligne","Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "François Cros", team: "toulouse", positions: ["Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Anthony Jelonch", team: "toulouse", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Jack Willis", team: "toulouse", positions: ["Troisième ligne"], rarity: "international", nat: "ANG" },
  { name: "Léo Banos", team: "toulouse", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mathis Castro-Ferreira", team: "toulouse", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Théo Ntamack", team: "toulouse", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Antoine Dupont", team: "toulouse", positions: ["Demi de mêlée"], rarity: "international", nat: "FRA" },
  { name: "Paul Graou", team: "toulouse", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Romain Ntamack", team: "toulouse", positions: ["Demi d'ouverture"], rarity: "epique", nat: "FRA" },
  { name: "Valentin Delpy", team: "toulouse", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Santiago Chocobares", team: "toulouse", positions: ["Centre"], rarity: "rare", nat: "ARG" },
  { name: "Pierre-Louis Barassi", team: "toulouse", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Tommaso Menoncello", team: "toulouse", positions: ["Centre"], rarity: "rare", nat: "ITA" },
  { name: "Célian Pouzelgues", team: "toulouse", positions: ["Centre"], rarity: "commune", nat: "TGA" },
  { name: "Kalvin Gourgues", team: "toulouse", positions: ["Centre","Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Teddy Thomas", team: "toulouse", positions: ["Ailier","Centre"], rarity: "rare", nat: "FRA" },
  { name: "Matthis Lebel", team: "toulouse", positions: ["Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Nelson Épée", team: "toulouse", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Ramos", team: "toulouse", positions: ["Arrière","Demi d'ouverture"], rarity: "international", nat: "FRA" },
  { name: "Blair Kinghorn", team: "toulouse", positions: ["Arrière","Demi d'ouverture"], rarity: "rare", nat: "ECO" },
  { name: "Ange Capuozzo", team: "toulouse", positions: ["Arrière","Ailier"], rarity: "epique", nat: "ITA" },
  { name: "Juan Cruz Mallia", team: "toulouse", positions: ["Arrière","Ailier"], rarity: "international", nat: "ARG" },
  { name: "Matias Remue", team: "toulouse", positions: ["Arrière"], rarity: "commune", nat: "BEL" },
  { name: "Jefferson Poirot", team: "ubb", positions: ["Pilier"], rarity: "rare", nat: "FRA", stats: {"vitesse":54,"puissance":84,"defense":78,"passe":70,"technique":71} },
  { name: "Ben Tameifuna", team: "ubb", positions: ["Pilier"], rarity: "epique", nat: "TGA", stats: {"vitesse":72,"puissance":93,"defense":86,"passe":81,"technique":86} },
  { name: "Sipili Falatea", team: "ubb", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Mathis Perchaud", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "FRA", stats: {"vitesse":52,"puissance":76,"defense":72,"passe":62,"technique":62} },
  { name: "Zinedine Aouad", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "FRA", stats: {"vitesse":60,"puissance":72,"defense":73,"passe":66,"technique":63} },
  { name: "Zaccharie Affane", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "FRA", stats: {"vitesse":65,"puissance":75,"defense":70,"passe":60,"technique":79} },
  { name: "Toma Taufa", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "TGA", stats: {"vitesse":64,"puissance":80,"defense":67,"passe":68,"technique":65} },
  { name: "Carlü Sadie", team: "ubb", positions: ["Pilier"], rarity: "epique", nat: "AFS", stats: {"vitesse":58,"puissance":82,"defense":72,"passe":60,"technique":78} },
  { name: "Lekso Kaulashvili", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "GEO", stats: {"vitesse":50,"puissance":80,"defense":72,"passe":60,"technique":60} },
  { name: "Lasha Pkhakadze", team: "ubb", positions: ["Pilier"], rarity: "commune", nat: "GEO", stats: {"vitesse":57,"puissance":72,"defense":75,"passe":60,"technique":67} },
  { name: "Maxime Lamothe", team: "ubb", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Connor Sa", team: "ubb", positions: ["Talonneur"], rarity: "commune", nat: "FRA", stats: {"vitesse":62,"puissance":74,"defense":70,"passe":65,"technique":65} },
  { name: "Gaëtan Barlot", team: "ubb", positions: ["Talonneur"], rarity: "rare", nat: "FRA", stats: {"vitesse":65,"puissance":84,"defense":76,"passe":67,"technique":75} },
  { name: "Cameron Woki", team: "ubb", positions: ["Deuxième ligne","Troisième ligne"], rarity: "epique", nat: "FRA", stats: {"vitesse":72,"puissance":75,"defense":87,"passe":68,"technique":81} },
  { name: "Adam Coleman", team: "ubb", positions: ["Deuxième ligne"], rarity: "rare", nat: "AUS", stats: {"vitesse":73,"puissance":81,"defense":73,"passe":69,"technique":82} },
  { name: "Alexander Moon", team: "ubb", positions: ["Deuxième ligne"], rarity: "rare", nat: "ANG", stats: {"vitesse":62,"puissance":75,"defense":72,"passe":74,"technique":79} },
  { name: "Cyril Cazeaux", team: "ubb", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA", stats: {"vitesse":63,"puissance":78,"defense":74,"passe":65,"technique":65} },
  { name: "Boris Palu", team: "ubb", positions: ["Deuxième ligne"], rarity: "epique", nat: "FRA", stats: {"vitesse":60,"puissance":83,"defense":75,"passe":68,"technique":80} },
  { name: "Pieter-Steph du Toit", team: "ubb", positions: ["Troisième ligne"], rarity: "epique", nat: "AFS" },
  { name: "Pierre Bochaton", team: "ubb", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":70,"puissance":76,"defense":75,"passe":68,"technique":68} },
  { name: "Jean-Luc Du Preez", team: "ubb", positions: ["Troisième ligne"], rarity: "epique", nat: "AFS" },
  { name: "Temo Matiu", team: "ubb", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA", stats: {"vitesse":80,"puissance":81,"defense":78,"passe":73,"technique":72} },
  { name: "Tiaan Jacobs", team: "ubb", positions: ["Troisième ligne"], rarity: "rare", nat: "AFS" },
  { name: "Marko Gazzotti", team: "ubb", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA", stats: {"vitesse":75,"puissance":86,"defense":80,"passe":79,"technique":80} },
  { name: "Tom Willis", team: "ubb", positions: ["Troisième ligne"], rarity: "epique", nat: "ANG", stats: {"vitesse":89,"puissance":88,"defense":80,"passe":82,"technique":84} },
  { name: "Maxime Lucu", team: "ubb", positions: ["Demi de mêlée"], rarity: "international", nat: "FRA" },
  { name: "Martin Page-Relo", team: "ubb", positions: ["Demi de mêlée"], rarity: "rare", nat: "ITA", stats: {"vitesse":77,"puissance":70,"defense":72,"passe":78,"technique":77} },
  { name: "Valentin Hutteau", team: "ubb", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Matthieu Jalibert", team: "ubb", positions: ["Demi d'ouverture"], rarity: "international", nat: "FRA" },
  { name: "Hugo Reus", team: "ubb", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA", stats: {"vitesse":74,"puissance":62,"defense":64,"passe":78,"technique":76} },
  { name: "Yoram Moefana", team: "ubb", positions: ["Centre"], rarity: "rare", nat: "FRA", stats: {"vitesse":76,"puissance":87,"defense":87,"passe":84,"technique":84} },
  { name: "Nicolas Depoortère", team: "ubb", positions: ["Centre"], rarity: "rare", nat: "FRA", stats: {"vitesse":74,"puissance":85,"defense":81,"passe":74,"technique":83} },
  { name: "Dan Du Plessis", team: "ubb", positions: ["Centre"], rarity: "commune", nat: "AFS", stats: {"vitesse":70,"puissance":80,"defense":76,"passe":70,"technique":76} },
  { name: "Rohan Janse Van Rensburg", team: "ubb", positions: ["Centre"], rarity: "rare", nat: "AFS", stats: {"vitesse":65,"puissance":74,"defense":76,"passe":75,"technique":82} },
  { name: "Adrien Drault", team: "ubb", positions: ["Centre"], rarity: "commune", nat: "FRA", stats: {"vitesse":72,"puissance":70,"defense":68,"passe":68,"technique":70} },
  { name: "Pablo Uberti", team: "ubb", positions: ["Centre","Ailier"], rarity: "commune", nat: "FRA", stats: {"vitesse":74,"puissance":76,"defense":70,"passe":72,"technique":72} },
  { name: "Arthur Retière", team: "ubb", positions: ["Ailier","Demi de mêlée"], rarity: "rare", nat: "FRA", stats: {"vitesse":82,"puissance":75,"defense":80,"passe":71,"technique":73} },
  { name: "Damian Penaud", team: "ubb", positions: ["Ailier","Centre"], rarity: "epique", nat: "FRA" },
  { name: "Louis Bielle-Biarrey", team: "ubb", positions: ["Ailier","Arrière"], rarity: "international", nat: "FRA" },
  { name: "Hugo Avogadro", team: "ubb", positions: ["Ailier"], rarity: "commune", nat: "FRA", stats: {"vitesse":80,"puissance":74,"defense":64,"passe":60,"technique":60} },
  { name: "Salesi Rayasi", team: "ubb", positions: ["Ailier","Arrière"], rarity: "rare", nat: "FIJ", stats: {"vitesse":86,"puissance":85,"defense":75,"passe":72,"technique":80} },
  { name: "Xan Mousques", team: "ubb", positions: ["Arrière"], rarity: "commune", nat: "FRA", stats: {"vitesse":78,"puissance":62,"defense":64,"passe":68,"technique":70} },
  { name: "Romain Buros", team: "ubb", positions: ["Arrière"], rarity: "rare", nat: "FRA", stats: {"vitesse":80,"puissance":76,"defense":80,"passe":80,"technique":80} },
  { name: "Eddy Ben Arous", team: "racing92", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Guram Gogichashvili", team: "racing92", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Hassane Kolingar", team: "racing92", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Gia Nurashvili", team: "racing92", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Lasha Kharaishvili", team: "racing92", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Demba Bamba", team: "racing92", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Taniela Tupou", team: "racing92", positions: ["Pilier"], rarity: "epique", nat: "AUS" },
  { name: "Janick Tarit", team: "racing92", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Diego Escobar", team: "racing92", positions: ["Talonneur"], rarity: "commune", nat: "CHI" },
  { name: "Robin Couly", team: "racing92", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Benjamin Boudou", team: "racing92", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Chouzenoux", team: "racing92", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Fabien Sanconnie", team: "racing92", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Junior Fisi'Ihoi", team: "racing92", positions: ["Deuxième ligne"], rarity: "commune", nat: "NZL" },
  { name: "Romain Taofifenua", team: "racing92", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Jonathan Hill", team: "racing92", positions: ["Deuxième ligne","Troisième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Thomas Lainault", team: "racing92", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Lekima Tagitagivalu", team: "racing92", positions: ["Deuxième ligne","Trosième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Nathan Hughes", team: "racing92", positions: ["Troisième ligne","Deuxième ligne"], rarity: "rare", nat: "FIJ" },
  { name: "Seru Uru", team: "racing92", positions: ["Troisième ligne"], rarity: "rare", nat: "FIJ" },
  { name: "Soumaila Camara", team: "racing92", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Jordan Joseph", team: "racing92", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Maxime Baudonne", team: "racing92", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ibrahim Diallo", team: "racing92", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Maxime Machenaud", team: "racing92", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Leo Carbonneau", team: "racing92", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Ugo Seunes", team: "racing92", positions: ["Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Geronimo Prisciantelli", team: "racing92", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ARG" },
  { name: "Antoine Gibert", team: "racing92", positions: ["Demi d'ouverture"], rarity: "epique", nat: "FRA" },
  { name: "Paul Costes", team: "racing92", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Sam James", team: "racing92", positions: ["Centre","Arière"], rarity: "commune", nat: "ANG" },
  { name: "Josua Tuisova", team: "racing92", positions: ["Centre","Ailier"], rarity: "epique", nat: "FIJ" },
  { name: "Joseph Manu", team: "racing92", positions: ["Centre"], rarity: "commune", nat: "AUS" },
  { name: "Wame Naituvi", team: "racing92", positions: ["Centre","Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Wilfried Hulleu", team: "racing92", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Selestino Ravutaumada", team: "racing92", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Vinaya Habosi", team: "racing92", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Max Spring", team: "racing92", positions: ["Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Shingi Manyarara", team: "racing92", positions: ["Trosième ligne"], rarity: "commune", nat: "ZIM" },
  { name: "Louis Penverne", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Nathan Fraissenon", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Alexandre Kaddouri", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Aleksandre Kuntelia", team: "lapelle", positions: ["Pilier"], rarity: "rare", nat: "GEO" },
  { name: "Karl Sorin", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Pierre Bourgarit", team: "lapelle", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Quentin Lespiaucq", team: "lapelle", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Tolu Latu", team: "lapelle", positions: ["Talonneur"], rarity: "rare", nat: "AUS" },
  { name: "Nikolozi Sutidze", team: "lapelle", positions: ["Talonneur"], rarity: "commune", nat: "GEO" },
  { name: "Watisoni Waqanisaravi", team: "lapelle", positions: ["Deuxième ligne","Troisième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Will Skelton", team: "lapelle", positions: ["Deuxième ligne"], rarity: "international", nat: "AUS" },
  { name: "Salmaan Moerat", team: "lapelle", positions: ["Deuxième ligne"], rarity: "rare", nat: "AFS" },
  { name: "Thomas Lavault", team: "lapelle", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Adélaide", team: "lapelle", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Paul Boudehent", team: "lapelle", positions: ["Troisième ligne","Deuxième ligne"], rarity: "international", nat: "FRA" },
  { name: "Grégory Alldritt", team: "lapelle", positions: ["Troisième ligne"], rarity: "international", nat: "FRA" },
  { name: "Théo Mcfarland", team: "lapelle", positions: ["Troisième ligne"], rarity: "rare", nat: "SAM" },
  { name: "Andy Timo", team: "lapelle", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Matthias Haddad", team: "lapelle", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Sam Tuifua", team: "lapelle", positions: ["Troisième ligne"], rarity: "commune", nat: "NZL" },
  { name: "Oscar Jegou", team: "lapelle", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Nolann Le Garrec", team: "lapelle", positions: ["Demi de mêlée"], rarity: "epique", nat: "FRA" },
  { name: "Thomas Berjon", team: "lapelle", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Christophe Loustalot", team: "lapelle", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Antoine Hastoy", team: "lapelle", positions: ["Demi d'ouverture","Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Ben Healy", team: "lapelle", positions: ["Demi d'ouverture"], rarity: "rare", nat: "IRL" },
  { name: "Simeli Daunivucu", team: "lapelle", positions: ["Centre","Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "David Kriel", team: "lapelle", positions: ["Centre"], rarity: "rare", nat: "AFS" },
  { name: "Semi Lagivala", team: "lapelle", positions: ["Centre","Ailier"], rarity: "rare", nat: "FIJ" },
  { name: "Levani Botia", team: "lapelle", positions: ["Centre","Troisième ligne"], rarity: "epique", nat: "FIJ" },
  { name: "Jonathan Danty", team: "lapelle", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Ulupano Seuteni", team: "lapelle", positions: ["Centre"], rarity: "commune", nat: "SAM" },
  { name: "Jules Favre", team: "lapelle", positions: ["Centre","Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Jack Nowell", team: "lapelle", positions: ["Ailier","Centre"], rarity: "commune", nat: "ANG" },
  { name: "Nathan Bollengier", team: "lapelle", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Hoani Bosmorin", team: "lapelle", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Ugo Pacome", team: "lapelle", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Dillyn Leyds", team: "lapelle", positions: ["Arrière","Ailier"], rarity: "epique", nat: "AFS" },
  { name: "Davit Niniashvili", team: "lapelle", positions: ["Arrière","Ailier"], rarity: "epique", nat: "GEO" },
  { name: "Dany Priso", team: "toulon", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Rabah Slimani", team: "toulon", positions: ["Pilier"], rarity: "epique", nat: "FRA" },
  { name: "Emerick Setiano", team: "toulon", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Beka Gigashvili", team: "toulon", positions: ["Pilier"], rarity: "rare", nat: "GEO" },
  { name: "Jean-Baptiste Gros", team: "toulon", positions: ["Pilier"], rarity: "international", nat: "FRA" },
  { name: "Kyle Sinckler", team: "toulon", positions: ["Pilier"], rarity: "rare", nat: "ANG" },
  { name: "Teddy Baubigny", team: "toulon", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Gianmarco Lucchesi", team: "toulon", positions: ["Talonneur"], rarity: "rare", nat: "ITA" },
  { name: "Pierre Damond", team: "toulon", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "David Ribbans", team: "toulon", positions: ["Deuxième ligne"], rarity: "international", nat: "ANG" },
  { name: "Corentin Mezou", team: "toulon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Lucianno Asevedo", team: "toulon", positions: ["Deuxième ligne"], rarity: "commune", nat: "ARG" },
  { name: "Junior Kpoku", team: "toulon", positions: ["Deuxième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Swan Rebbadj", team: "toulon", positions: ["Deuxième ligne","Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Matthias Halagahu", team: "toulon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Judicaël Cancoriet", team: "toulon", positions: ["Troisième ligne","Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Charles Ollivon", team: "toulon", positions: ["Troisième ligne"], rarity: "international", nat: "FRA" },
  { name: "Jules Coulon", team: "toulon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Joe Quere-Karaba", team: "toulon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Patrick Tuifua", team: "toulon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Zach Mercer", team: "toulon", positions: ["Troisième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Esteban Abadie", team: "toulon", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Lewis Ludlam", team: "toulon", positions: ["Troisième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Baptiste Serin", team: "toulon", positions: ["Demi de mêlée"], rarity: "epique", nat: "FRA" },
  { name: "Ben White", team: "toulon", positions: ["Demi de mêlée"], rarity: "rare", nat: "ECO" },
  { name: "Jules Danglot", team: "toulon", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Clovis Le Bail", team: "toulon", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Tomas Albornoz", team: "toulon", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ARG" },
  { name: "Matéo Garcia", team: "toulon", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Luka Keletaona", team: "toulon", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Gaël Fickou", team: "toulon", positions: ["Centre"], rarity: "epique", nat: "FRA" },
  { name: "Antoine Frisch", team: "toulon", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Huw Jones", team: "toulon", positions: ["Centre"], rarity: "rare", nat: "ECO" },
  { name: "Juan Ignacio Brex", team: "toulon", positions: ["Centre"], rarity: "rare", nat: "ITA" },
  { name: "Oliver Cowie", team: "toulon", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Ma'a Nonu", team: "toulon", positions: ["Centre"], rarity: "legendaire", nat: "NZL" },
  { name: "Mathieu Smaïli", team: "toulon", positions: ["Centre","Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Rayan Rebbadj", team: "toulon", positions: ["Centre","Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Gabbin Villière", team: "toulon", positions: ["Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Setariki Tuicuvu", team: "toulon", positions: ["Ailier","Arrière"], rarity: "commune", nat: "FIJ" },
  { name: "Apeta Narogo", team: "toulon", positions: ["Ailier"], rarity: "rare", nat: "FIJ" },
  { name: "Gael Dréan", team: "toulon", positions: ["Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Melvyn Jaminet", team: "toulon", positions: ["Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Marius Domon", team: "toulon", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Mathis Ferté", team: "toulon", positions: ["Arrière","Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Cristian Ojovan", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "MDA" },
  { name: "Régis Montagne", team: "clermont", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Giorgi Akhaladze", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Giorgi Dzmanashvili", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Matheo Frisach", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Sacha Lotrian", team: "clermont", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Giga Tutisani", team: "clermont", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Barnabé Massa", team: "clermont", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Peniami Narisia", team: "clermont", positions: ["Talonneur"], rarity: "commune", nat: "FIJ" },
  { name: "Etienne Fourcade", team: "clermont", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Marcos Kremer", team: "clermont", positions: ["Deuxième ligne","Troisième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Thibaud Lanen", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Oskar Rixen", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "ALL" },
  { name: "Darcy Swain", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "AUS" },
  { name: "Thomas Ceyte", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Léo Michaux", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Tevita Ratuva", team: "clermont", positions: ["Deuxième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Selevasio Tolofua", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Killian Tixeront", team: "clermont", positions: ["Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Lucas Dessaigne", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Kevin Noah", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Anthime Hemery", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Pio Muarua", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Pita-Gus Sowakula", team: "clermont", positions: ["Troisième ligne"], rarity: "rare", nat: "NZL" },
  { name: "Baptiste Veschambre", team: "clermont", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Germain", team: "clermont", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Jauneau", team: "clermont", positions: ["Demi de mêlée"], rarity: "epique", nat: "FRA" },
  { name: "Lucas Zamora", team: "clermont", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Harry Plummer", team: "clermont", positions: ["Demi d'ouverture"], rarity: "epique", nat: "NZL" },
  { name: "Justin Bouraux", team: "clermont", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Léon Darricarrère", team: "clermont", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "AJ Lam", team: "clermont", positions: ["Centre"], rarity: "rare", nat: "NZL" },
  { name: "George Moala", team: "clermont", positions: ["Centre"], rarity: "rare", nat: "TGA" },
  { name: "Timeo Frier", team: "clermont", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Alivereti Loaloa", team: "clermont", positions: ["Centre"], rarity: "commune", nat: "FIJ" },
  { name: "Alivereti Raka", team: "clermont", positions: ["Ailier"], rarity: "epique", nat: "FRA" },
  { name: "Joris Jurand", team: "clermont", positions: ["Ailier","Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Bautista Delguy", team: "clermont", positions: ["Ailier"], rarity: "rare", nat: "ARG" },
  { name: "Yerim Fall", team: "clermont", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Kylan Hamdaoui", team: "clermont", positions: ["Arrière","Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Axel Guillaud", team: "clermont", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Etene Nanai-Seturo", team: "clermont", positions: ["Arrière"], rarity: "rare", nat: "NZL" },
  { name: "Tevita Tatafu", team: "bayonne", positions: ["Pilier"], rarity: "rare", nat: "TGA" },
  { name: "Swan Cormenier", team: "bayonne", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Luke Tagi", team: "bayonne", positions: ["Pilier"], rarity: "commune", nat: "FIJ" },
  { name: "Andy Bordelai", team: "bayonne", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Lasha Macharashvili", team: "bayonne", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Igniacio Calles", team: "bayonne", positions: ["Pilier"], rarity: "rare", nat: "ARG" },
  { name: "Guillaume Cramont", team: "bayonne", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Facundo Bosch", team: "bayonne", positions: ["Talonneur"], rarity: "rare", nat: "ARG" },
  { name: "Lucas Martin", team: "bayonne", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Arthur Iturria", team: "bayonne", positions: ["Deuxième ligne","Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Lucas Paulos", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "ARG" },
  { name: "Denis Marchois", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ewan Johnson", team: "bayonne", positions: ["Deuxième ligne"], rarity: "rare", nat: "ECO" },
  { name: "Matthieu Uhila", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mael Perrin", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ruben Van Heerden", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "AFS" },
  { name: "Brian Alainu'uese", team: "bayonne", positions: ["Deuxième ligne"], rarity: "commune", nat: "SAM" },
  { name: "Killian Geraci", team: "bayonne", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Rodrigo Bruni", team: "bayonne", positions: ["Troisième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Pierre Huguet", team: "bayonne", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Heguy", team: "bayonne", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Esteban Capilla", team: "bayonne", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Raphael Darquier", team: "bayonne", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Giovanni Habel-Kuffner", team: "bayonne", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Rob Leota", team: "bayonne", positions: ["Troisième ligne"], rarity: "rare", nat: "AUS" },
  { name: "Alexandre Fischer", team: "bayonne", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Guillaume Rouet", team: "bayonne", positions: ["Demi de mêlée"], rarity: "rare", nat: "ESP" },
  { name: "Herschel Jantjies", team: "bayonne", positions: ["Demi de mêlée"], rarity: "rare", nat: "AFS" },
  { name: "Léo Coly", team: "bayonne", positions: ["Demi de mêlée","Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Joris Segonds", team: "bayonne", positions: ["Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Rob Du Preez", team: "bayonne", positions: ["Demi d'ouverture"], rarity: "rare", nat: "AFS" },
  { name: "Manu Tuilagi", team: "bayonne", positions: ["Centre"], rarity: "epique", nat: "ANG" },
  { name: "Sireli Maqala", team: "bayonne", positions: ["Centre","Ailier"], rarity: "epique", nat: "FIJ" },
  { name: "Federico Mori", team: "bayonne", positions: ["Centre","Ailier"], rarity: "commune", nat: "ITA" },
  { name: "Guillaume Martocq", team: "bayonne", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Arnaud Erbinartegaray", team: "bayonne", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Viliame Tutuvuli", team: "bayonne", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Mateo Carreras", team: "bayonne", positions: ["Ailier"], rarity: "commune", nat: "ARG" },
  { name: "Rémy Baget", team: "bayonne", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Nadir Megdoud", team: "bayonne", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Madosh Tambwe", team: "bayonne", positions: ["Ailier"], rarity: "rare", nat: "RDC" },
  { name: "Cheikh Tiberghien", team: "bayonne", positions: ["Arrière","Centre"], rarity: "commune", nat: "FRA" },
  { name: "Tom Spring", team: "bayonne", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Yohan Orabé", team: "bayonne", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Laclayat", team: "pau", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Alexandre Etchebehere", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Guram Papidze", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Lesko Kaulashvili", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Hugo Parrou", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Daniel Bibi-Bizewu", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Sébastien Senca", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Siate Tokolahi", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "TGA" },
  { name: "Jon Zabala", team: "pau", positions: ["Pilier"], rarity: "commune", nat: "ESP" },
  { name: "Lucas Rey", team: "pau", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Youri Delhommel", team: "pau", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Julian Montoya", team: "pau", positions: ["Talonneur"], rarity: "rare", nat: "ARG" },
  { name: "Jimi Maximin", team: "pau", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Brent Liufau", team: "pau", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Hugo Auradou", team: "pau", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Mickael Capelli", team: "pau", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Jolmes", team: "pau", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Pesenti", team: "pau", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Bastien Vergnes-Taillefer", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Facundo Isa", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Santiago Grondona", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Beka Gorgadze", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "GEO" },
  { name: "Reece Hewat", team: "pau", positions: ["Troisième ligne"], rarity: "rare", nat: "AUS" },
  { name: "Sacha Zegueur", team: "pau", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Rémi Couty", team: "pau", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Loïc Credoz", team: "pau", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Luke Whitelock", team: "pau", positions: ["Troisième ligne"], rarity: "legendaire", nat: "NZL" },
  { name: "Thibault Daubagna", team: "pau", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Thomas Souverbie", team: "pau", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Gonzalo Garcia", team: "pau", positions: ["Demi de mêlée"], rarity: "commune", nat: "ARG" },
  { name: "Joe Simmonds", team: "pau", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ANG" },
  { name: "Axel Desperes", team: "pau", positions: ["Demi d'ouverture","Centre"], rarity: "commune", nat: "FRA" },
  { name: "Clément Mondinat", team: "pau", positions: ["Demi d'ouverture","Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Émilien Gailleton", team: "pau", positions: ["Centre"], rarity: "epique", nat: "FRA" },
  { name: "Fabien Brau-Boirie", team: "pau", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Nathan Decron", team: "pau", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Tumua Manu", team: "pau", positions: ["Centre"], rarity: "commune", nat: "SAM" },
  { name: "Clément Valentino", team: "pau", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Clement Laporte", team: "pau", positions: ["Ailier","Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Aaron Grandidier", team: "pau", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Théo Attissogbe", team: "pau", positions: ["Ailier","Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Grégoire Arfeuil", team: "pau", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Rodrigo Marta", team: "pau", positions: ["Ailier"], rarity: "commune", nat: "POR" },
  { name: "Jack Maddocks", team: "pau", positions: ["Arrière"], rarity: "rare", nat: "AUS" },
  { name: "Joachim Senga Kouo", team: "pau", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Moukoro", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Opeti Helu", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "TGA" },
  { name: "Jérôme Rey", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Irakli Aptsiauri", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Hamza Kaabeche", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Gallo", team: "lyon", positions: ["Pilier"], rarity: "rare", nat: "ARG" },
  { name: "Tim Hoyt", team: "lyon", positions: ["Pilier"], rarity: "commune", nat: "ANG" },
  { name: "Camille Chat", team: "lyon", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Guillaume Marchand", team: "lyon", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Mathis Sarragallet", team: "lyon", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Felix Lambey", team: "lyon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mickaël Guillard", team: "lyon", positions: ["Deuxième ligne","Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Théo William", team: "lyon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Beka Shvangiradze", team: "lyon", positions: ["Troisième ligne"], rarity: "rare", nat: "GEO" },
  { name: "Beka Saginadze", team: "lyon", positions: ["Troisième ligne"], rarity: "rare", nat: "GEO" },
  { name: "Dylan Cretin", team: "lyon", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Maxime Gouzou", team: "lyon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Liam Allen", team: "lyon", positions: ["Troisième ligne"], rarity: "commune", nat: "NZL" },
  { name: "Marvin Okuya", team: "lyon", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Couilloud", team: "lyon", positions: ["Demi de mêlée"], rarity: "epique", nat: "FRA" },
  { name: "Esteban Gonzalez", team: "lyon", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Charlie Cassang", team: "lyon", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Sanele Nohamba", team: "lyon", positions: ["Demi de mêlée"], rarity: "commune", nat: "AFS" },
  { name: "Leo Berdeu", team: "lyon", positions: ["Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Paddy Jackson", team: "lyon", positions: ["Demi d'ouverture"], rarity: "rare", nat: "IRL" },
  { name: "Martin Méliande", team: "lyon", positions: ["Demi d'ouverture","Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Adrien Seguret", team: "lyon", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Alfred Parisien", team: "lyon", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Thibaut Regard", team: "lyon", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Iosefo Masi", team: "lyon", positions: ["Centre"], rarity: "commune", nat: "FIJ" },
  { name: "Josiah Maraku", team: "lyon", positions: ["Centre"], rarity: "rare", nat: "NZL" },
  { name: "Theo Millet", team: "lyon", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Jiuta Wainiqolo", team: "lyon", positions: ["Ailier"], rarity: "epique", nat: "FIJ" },
  { name: "Ethan Dumortier", team: "lyon", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Monty Ioane", team: "lyon", positions: ["Ailier"], rarity: "rare", nat: "ITA" },
  { name: "Arthur Mathiron", team: "lyon", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Alexandre Tchaptchet", team: "lyon", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Gabin Lorre", team: "lyon", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Sam Simmonds", team: "lyon", positions: ["Trosième ligne"], rarity: "rare", nat: "ANG" },
  { name: "Levan Chilachava", team: "castres", positions: ["Pilier"], rarity: "rare", nat: "GEO" },
  { name: "Will Collier", team: "castres", positions: ["Pilier"], rarity: "commune", nat: "ANG" },
  { name: "Quentin Walcker", team: "castres", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Lois Guerois-Galisson", team: "castres", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Nicolas Corato", team: "castres", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Alex Burin", team: "castres", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Mael Turpin", team: "castres", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Pierre Colonna", team: "castres", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Loris Zarantonello", team: "castres", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Teddy Durand", team: "castres", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Tom Staniforth", team: "castres", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Chris Gabriel", team: "castres", positions: ["Deuxième ligne"], rarity: "commune", nat: "NZL" },
  { name: "Alexey Konnov", team: "castres", positions: ["Deuxième ligne"], rarity: "rare", nat: "RUS" },
  { name: "Leone Nakarawa", team: "castres", positions: ["Deuxième ligne"], rarity: "legendaire", nat: "FIJ" },
  { name: "Florent Vanverberghe", team: "castres", positions: ["Deuxième ligne","Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Paul Jedrasiak", team: "castres", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Gauthier Maravat", team: "castres", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Guillaume Ducat", team: "castres", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mathieu Babillot", team: "castres", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Abraham Papali'i", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "NZL" },
  { name: "Baptiste Cope", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Baptiste Delaporte", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Feibyan Tukino", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Simon Meka", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Veresa Ramototabua", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Dalton Papali'i", team: "castres", positions: ["Troisième ligne"], rarity: "international", nat: "NZL" },
  { name: "Santiago Arata", team: "castres", positions: ["Demi de mêlée"], rarity: "epique", nat: "URU" },
  { name: "Gauthier Doubrère", team: "castres", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Jeremy Fernandez", team: "castres", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Louis Le Brun", team: "castres", positions: ["Demi d'ouverture","Centre"], rarity: "rare", nat: "FRA" },
  { name: "Vilimoni Botitu", team: "castres", positions: ["Centre","Demi d'ouverture"], rarity: "rare", nat: "FIJ" },
  { name: "Adrea Cocagi", team: "castres", positions: ["Centre"], rarity: "commune", nat: "FIJ" },
  { name: "Jack Goodhue", team: "castres", positions: ["Centre"], rarity: "epique", nat: "NZL" },
  { name: "Taylor Gontineac", team: "castres", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Atu Manu", team: "castres", positions: ["Centre"], rarity: "rare", nat: "FIJ" },
  { name: "Rémy Baget", team: "castres", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Adam Vargas", team: "castres", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Christian Ambadiang", team: "castres", positions: ["Ailier"], rarity: "rare", nat: "CAM" },
  { name: "Vuate Karawalevu ", team: "castres", positions: ["Ailier"], rarity: "commune", nat: "FIJ" },
  { name: "Geoffrey Palis", team: "castres", positions: ["Arrière","Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Théo Chabouni", team: "castres", positions: ["Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Lucas Tabarot", team: "montpellier", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Mohamed Haouas", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Wilfrid Hounkpatin", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "SEN" },
  { name: "Valentin Welsch", team: "montpellier", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Reda Wardi", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Baptiste Erdocio", team: "montpellier", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Luka Japaridze", team: "montpellier", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Christopher Tolofua", team: "montpellier", positions: ["Talonneur","Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Lyam Akrab", team: "montpellier", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Ricky Riccitelli", team: "montpellier", positions: ["Talonneur"], rarity: "commune", nat: "AFS" },
  { name: "Jordan Uelese", team: "montpellier", positions: ["Talonneur"], rarity: "rare", nat: "AUS" },
  { name: "Tyler Duguid", team: "montpellier", positions: ["Deuxième ligne"], rarity: "commune", nat: "CAN" },
  { name: "Adam Beard", team: "montpellier", positions: ["Deuxième ligne"], rarity: "commune", nat: "PDG" },
  { name: "Bastien Chalureau", team: "montpellier", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Florian Verhaeghe", team: "montpellier", positions: ["Deuxième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Yacouba Camara", team: "montpellier", positions: ["Troisième ligne","Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Billy Vunipola", team: "montpellier", positions: ["Troisième ligne"], rarity: "international", nat: "ANG" },
  { name: "Langi Gleeson", team: "montpellier", positions: ["Troisième ligne"], rarity: "commune", nat: "AUS" },
  { name: "Alexander Masibaka", team: "montpellier", positions: ["Troisième ligne"], rarity: "commune", nat: "AUS" },
  { name: "Lenni Nouchi", team: "montpellier", positions: ["Troisième ligne"], rarity: "epique", nat: "FRA" },
  { name: "Alexandre Bécognée", team: "montpellier", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ali Price", team: "montpellier", positions: ["Demi de mêlée"], rarity: "rare", nat: "ECO" },
  { name: "Alexis Bernadet", team: "montpellier", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Sébastien Bézy", team: "montpellier", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Adam Hastings", team: "montpellier", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ECO" },
  { name: "Domingo Miotti", team: "montpellier", positions: ["Demi d'ouverture"], rarity: "commune", nat: "ARG" },
  { name: "Lennox Anyanwu", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "ANG" },
  { name: "Arthur Vincent", team: "montpellier", positions: ["Centre"], rarity: "rare", nat: "FRA" },
  { name: "Justo Piccardo", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "ARG" },
  { name: "Auguste Cadot", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Karl Martin", team: "montpellier", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Dimitri Delibes", team: "montpellier", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Donovan Taofifenua", team: "montpellier", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Maël Moustin", team: "montpellier", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Gabriel Ngandebe", team: "montpellier", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Stuart Hogg", team: "montpellier", positions: ["Arrière","Demi d'ouverture"], rarity: "epique", nat: "ECO" },
  { name: "Jon Echegaray", team: "montpellier", positions: ["Arrière"], rarity: "commune", nat: "FRA" },
  { name: "Tom Banks", team: "montpellier", positions: ["Arrière"], rarity: "commune", nat: "AUS" },
  { name: "Paul Alo-Emile", team: "stadefr", positions: ["Pilier"], rarity: "rare", nat: "SAM" },
  { name: "Sergo Abramishvili", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Moses Alo-Emile", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "SAM" },
  { name: "Giorgi Melikidze", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "GEO" },
  { name: "Jack Iscaro", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "USA" },
  { name: "Isaac Koffi", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Bué", team: "stadefr", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Thierry Paiva", team: "stadefr", positions: ["Pilier"], rarity: "rare", nat: "FRA" },
  { name: "Giacomo Nicotera", team: "stadefr", positions: ["Talonneur"], rarity: "rare", nat: "ITA" },
  { name: "Lucas Peyresblanques", team: "stadefr", positions: ["Talonneur"], rarity: "rare", nat: "FRA" },
  { name: "Alvaro Garcia", team: "stadefr", positions: ["Talonneur"], rarity: "commune", nat: "ESP" },
  { name: "Tomasi Maka", team: "stadefr", positions: ["Talonneur"], rarity: "commune", nat: "NZL" },
  { name: "Paul Gabrillagues", team: "stadefr", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Petero Mailulu", team: "stadefr", positions: ["Deuxième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Pierre-Henri Azagoh", team: "stadefr", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Jacques Botha", team: "stadefr", positions: ["Deuxième ligne"], rarity: "commune", nat: "AFS" },
  { name: "Setareki Turagacoke", team: "stadefr", positions: ["Deuxième ligne"], rarity: "commune", nat: "FIJ" },
  { name: "Sekou Macalou", team: "stadefr", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Yoan Tanga", team: "stadefr", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Romain Briatte", team: "stadefr", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Tanginoa Halaifonua", team: "stadefr", positions: ["Troisième ligne"], rarity: "rare", nat: "TGA" },
  { name: "Mathieu Hirigoyen", team: "stadefr", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ryan Chapuis", team: "stadefr", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Juan Martin Scelzo", team: "stadefr", positions: ["Troisième ligne"], rarity: "commune", nat: "ARG" },
  { name: "Paul Abadie", team: "stadefr", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Tawera Kerr-Barlow", team: "stadefr", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA" },
  { name: "Thibaut Motassi", team: "stadefr", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Martin Blum", team: "stadefr", positions: ["Demi de mêlée"], rarity: "commune", nat: "FRA" },
  { name: "Louis Carbonel", team: "stadefr", positions: ["Demi d'ouverture"], rarity: "rare", nat: "FRA" },
  { name: "Léo Barré", team: "stadefr", positions: ["Demi d'ouverture","Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Louis Foursans", team: "stadefr", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Ihaia West", team: "stadefr", positions: ["Demi d'ouverture"], rarity: "commune", nat: "NZL" },
  { name: "Jeremy Ward", team: "stadefr", positions: ["Centre"], rarity: "rare", nat: "AFS" },
  { name: "Julien Delbouis", team: "stadefr", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Noah Nene", team: "stadefr", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Tani Vili", team: "stadefr", positions: ["Centre","Troisième ligne"], rarity: "rare", nat: "FRA" },
  { name: "Alivereti Duguivalu", team: "stadefr", positions: ["Ailier","Centre"], rarity: "rare", nat: "FIJ", stats: {"vitesse":86,"puissance":82,"defense":72,"passe":70,"technique":75} },
  { name: "Lester Etien", team: "stadefr", positions: ["Ailier"], rarity: "rare", nat: "FRA" },
  { name: "Peniasi Dakuwaqa", team: "stadefr", positions: ["Ailier"], rarity: "rare", nat: "FIJ" },
  { name: "Samuel Ezeala", team: "stadefr", positions: ["Ailier","Centre"], rarity: "commune", nat: "ESP" },
  { name: "Mathis Ibo", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Yannick Lodjro", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Rufus Mclean", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "USA" },
  { name: "Léo Monin", team: "stadefr", positions: ["Arrière"], rarity: "commune", nat: "AUS" },
  { name: "Enzo Forletta", team: "perpignan", positions: ["Pilier"], rarity: "rare", nat: "FRA", stats: {"vitesse":58,"puissance":84,"defense":78,"passe":69,"technique":68} },
  { name: "Giorgi Tetrashvili", team: "perpignan", positions: ["Pilier"], rarity: "rare", nat: "GEO", stats: {"vitesse":50,"puissance":82,"defense":76,"passe":66,"technique":73} },
  { name: "Kieran Brookes", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "ANG", stats: {"vitesse":48,"puissance":80,"defense":72,"passe":62,"technique":64} },
  { name: "Bruce Devaux", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "FRA", stats: {"vitesse":50,"puissance":76,"defense":70,"passe":60,"technique":65} },
  { name: "Lorencio Boyer Gallardo", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "FRA", stats: {"vitesse":50,"puissance":74,"defense":68,"passe":58,"technique":58} },
  { name: " Pietro Ceccarelli", team: "perpignan", positions: ["Pilier"], rarity: "rare", nat: "ITA", stats: {"vitesse":48,"puissance":84,"defense":76,"passe":66,"technique":66} },
  { name: " Marco Riccioni", team: "perpignan", positions: ["Pilier"], rarity: "rare", nat: "ITA", stats: {"vitesse":52,"puissance":84,"defense":78,"passe":68,"technique":68} },
  { name: "Cedate Gomes Sa", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Ignacio Ruiz", team: "perpignan", positions: ["Talonneur"], rarity: "rare", nat: "ARG", stats: {"vitesse":68,"puissance":82,"defense":76,"passe":74,"technique":75} },
  { name: "Seilala Lam", team: "perpignan", positions: ["Talonneur"], rarity: "commune", nat: "SAM", stats: {"vitesse":62,"puissance":74,"defense":78,"passe":65,"technique":65} },
  { name: "Victor Montgaillard", team: "perpignan", positions: ["Talonneur"], rarity: "commune", nat: "FRA", stats: {"vitesse":60,"puissance":74,"defense":70,"passe":65,"technique":65} },
  { name: "Mathys Lotrian", team: "perpignan", positions: ["Talonneur"], rarity: "commune", nat: "FRA", stats: {"vitesse":60,"puissance":72,"defense":70,"passe":62,"technique":62} },
  { name: "Posolo Tuilagi", team: "perpignan", positions: ["Deuxième ligne"], rarity: "rare", nat: "FRA", stats: {"vitesse":57,"puissance":92,"defense":78,"passe":70,"technique":70} },
  { name: "Tristan Labouteley", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":58,"puissance":78,"defense":75,"passe":68,"technique":68} },
  { name: "Jacobus van Tonder", team: "perpignan", positions: ["Deuxième ligne","Troisième ligne"], rarity: "commune", nat: "AFS", stats: {"vitesse":64,"puissance":78,"defense":74,"passe":66,"technique":65} },
  { name: "Mathieu Tanguy", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":56,"puissance":76,"defense":72,"passe":64,"technique":64} },
  { name: "Bastien Chinarro", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":58,"puissance":74,"defense":70,"passe":62,"technique":62} },
  { name: "Jonny Gray", team: "perpignan", positions: ["Deuxième ligne"], rarity: "rare", nat: "ECO", stats: {"vitesse":58,"puissance":84,"defense":88,"passe":72,"technique":74} },
  { name: "José Madeira", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "POR", stats: {"vitesse":60,"puissance":76,"defense":72,"passe":66,"technique":64} },
  { name: "Davit Lagvilava", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "GEO", stats: {"vitesse":56,"puissance":75,"defense":72,"passe":60,"technique":60} },
  { name: "Adrien Warion", team: "perpignan", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":58,"puissance":76,"defense":72,"passe":66,"technique":66} },
  { name: "Lachlan Swinton", team: "perpignan", positions: ["Troisième ligne"], rarity: "commune", nat: "AUS", stats: {"vitesse":68,"puissance":80,"defense":76,"passe":65,"technique":65} },
  { name: "Joaquín Oviedo", team: "perpignan", positions: ["Troisième ligne"], rarity: "epique", nat: "ARG", stats: {"vitesse":75,"puissance":88,"defense":85,"passe":83,"technique":83} },
  { name: "Noe Della Schiava", team: "perpignan", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":68,"puissance":74,"defense":72,"passe":64,"technique":65} },
  { name: "Jovan Sreckovic", team: "perpignan", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":62,"puissance":75,"defense":77,"passe":62,"technique":65} },
  { name: "Mattéo Le Corvec", team: "perpignan", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":70,"puissance":76,"defense":74,"passe":66,"technique":66} },
  { name: "Peceli Yato", team: "perpignan", positions: ["Troisième ligne"], rarity: "epique", nat: "FIJ", stats: {"vitesse":68,"puissance":87,"defense":84,"passe":81,"technique":82} },
  { name: "Lucas Velarte", team: "perpignan", positions: ["Troisième ligne"], rarity: "rare", nat: "FRA", stats: {"vitesse":70,"puissance":82,"defense":78,"passe":72,"technique":72} },
  { name: "Peceli Yato", team: "perpignan", positions: ["Troisième ligne","Deuxième ligne"], rarity: "rare", nat: "FIJ", stats: {"vitesse":68,"puissance":87,"defense":84,"passe":81,"technique":82} },
  { name: "Tom Ecochard", team: "perpignan", positions: ["Demi de mêlée"], rarity: "rare", nat: "FRA", stats: {"vitesse":78,"puissance":65,"defense":70,"passe":80,"technique":80} },
  { name: "James Hall", team: "perpignan", positions: ["Demi de mêlée"], rarity: "commune", nat: "AFS", stats: {"vitesse":74,"puissance":65,"defense":68,"passe":76,"technique":72} },
  { name: "Luke McGrath", team: "perpignan", positions: ["Demi de mêlée"], rarity: "epique", nat: "IRL", stats: {"vitesse":80,"puissance":70,"defense":85,"passe":88,"technique":86} },
  { name: "Antoine Aucagne", team: "perpignan", positions: ["Demi d'ouverture","Arrière"], rarity: "rare", nat: "FRA", stats: {"vitesse":76,"puissance":65,"defense":77,"passe":80,"technique":80} },
  { name: "Jake McIntyre", team: "perpignan", positions: ["Demi d'ouverture","Arrière"], rarity: "rare", nat: "AUS", stats: {"vitesse":78,"puissance":66,"defense":72,"passe":82,"technique":80} },
  { name: "Gabin Kretchmann", team: "perpignan", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA", stats: {"vitesse":70,"puissance":60,"defense":65,"passe":70,"technique":72} },
  { name: "Tristan Tedder", team: "perpignan", positions: ["Demi d'ouverture","Arrière"], rarity: "commune", nat: "AFS", stats: {"vitesse":78,"puissance":62,"defense":65,"passe":78,"technique":78} },
  { name: "Paolo Garbisi", team: "perpignan", positions: ["Demi d'ouverture"], rarity: "rare", nat: "ITA", stats: {"vitesse":81,"puissance":82,"defense":83,"passe":81,"technique":83} },
  { name: "Jerónimo de la Fuente", team: "perpignan", positions: ["Centre"], rarity: "rare", nat: "ARG", stats: {"vitesse":74,"puissance":82,"defense":84,"passe":76,"technique":78} },
  { name: "Eneriko Buliruarua", team: "perpignan", positions: ["Centre","Ailier"], rarity: "commune", nat: "FIJ", stats: {"vitesse":76,"puissance":78,"defense":74,"passe":68,"technique":72} },
  { name: "Duncan Paia'Aua", team: "perpignan", positions: ["Centre"], rarity: "commune", nat: "SAM", stats: {"vitesse":76,"puissance":76,"defense":70,"passe":72,"technique":72} },
  { name: "Job Poulet", team: "perpignan", positions: ["Centre"], rarity: "commune", nat: "FRA", stats: {"vitesse":72,"puissance":70,"defense":66,"passe":66,"technique":68} },
  { name: "Maelan Rabut", team: "perpignan", positions: ["Centre"], rarity: "commune", nat: "FRA", stats: {"vitesse":64,"puissance":75,"defense":73,"passe":66,"technique":73} },
  { name: "Braydon Eenor", team: "perpignan", positions: ["Centre"], rarity: "rare", nat: "NZL", stats: {"vitesse":82,"puissance":78,"defense":78,"passe":78,"technique":82} },
  { name: "Sevu Reece", team: "perpignan", positions: ["Ailier"], rarity: "international", nat: "NZL", stats: {"vitesse":92,"puissance":82,"defense":75,"passe":83,"technique":88} },
  { name: "Maxim Granell", team: "perpignan", positions: ["Ailier"], rarity: "commune", nat: "FRA", stats: {"vitesse":78,"puissance":62,"defense":75,"passe":70,"technique":72} },
  { name: "Jefferson-Lee Joseph", team: "perpignan", positions: ["Ailier","Arrière"], rarity: "rare", nat: "FRA", stats: {"vitesse":90,"puissance":72,"defense":68,"passe":72,"technique":78} },
  { name: "Setareki Toganiyadrava", team: "perpignan", positions: ["Ailier"], rarity: "commune", nat: "FIJ", stats: {"vitesse":82,"puissance":76,"defense":64,"passe":64,"technique":68} },
  { name: "Théo Forner", team: "perpignan", positions: ["Ailier","Arrière"], rarity: "rare", nat: "FRA", stats: {"vitesse":85,"puissance":70,"defense":70,"passe":74,"technique":74} },
  { name: "Ugo Boniface", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA", stats: {"vitesse":50,"puissance":76,"defense":70,"passe":62,"technique":61} },
  { name: "Giorgi Beria", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA", stats: {"vitesse":52,"puissance":76,"defense":72,"passe":64,"technique":65} },
  { name: "Wayan De Benedittis", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Simon Bourgeois", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Hugo Djehi", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "FRA" },
  { name: "Santiago Medrano", team: "vannes", positions: ["Pilier"], rarity: "rare", nat: "ARG" },
  { name: "Nick Schonert", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "AFS" },
  { name: "Théo Béziat", team: "vannes", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Mills Sanerivi", team: "vannes", positions: ["Talonneur"], rarity: "commune", nat: "NZL" },
  { name: "Dave Cherry", team: "vannes", positions: ["Talonneur"], rarity: "commune", nat: "ECO" },
  { name: "Mattéo Desjeux", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Thomas Geffré", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Eric Marks", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "ALL" },
  { name: "Timothé Mézou", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Matias Alemanno", team: "vannes", positions: ["Deuxième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Simon Augry", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Steeve Blanc-Mappaz", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Léon Boulier", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Joseph Edwards", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "NZL" },
  { name: "Francisco Gorrissen", team: "vannes", positions: ["Troisième ligne"], rarity: "epique", nat: "ARG" },
  { name: "Edoardo Iachizzi", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "ITA" },
  { name: "Sione Kalamafoni", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "TGA" },
  { name: "Kitione Kamikamica", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "FIJ" },
  { name: "Juan-Bautista Pedemonte", team: "vannes", positions: ["Troisième ligne"], rarity: "rare", nat: "ARG" },
  { name: "Mikheil Alania", team: "vannes", positions: ["Demi de mêlée"], rarity: "commune", nat: "GEO" },
  { name: "Michael Ruru", team: "vannes", positions: ["Demi de mêlée"], rarity: "rare", nat: "NZL" },
  { name: "Simi Kurivoli", team: "vannes", positions: ["Demi de mêlée"], rarity: "commune", nat: "FIJ" },
  { name: "Maxime Lafage", team: "vannes", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Jean Cotarmanac'h", team: "vannes", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Pierre Popelin", team: "vannes", positions: ["Demi d'ouverture","Arrière"], rarity: "rare", nat: "FRA" },
  { name: "Robin Taccola", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Eliott Roudil", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Pierre Boudehent", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Marin Boulier", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Enzo Benmegal", team: "vannes", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Romaric Camou", team: "vannes", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Ben Stevenson", team: "vannes", positions: ["Ailier"], rarity: "commune", nat: "ANG" },
  { name: "Nathanaël Hulleu", team: "vannes", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Paul Surano", team: "vannes", positions: ["Arrière"], rarity: "epique", nat: "FRA" },
  { name: "Anthony Bouthier", team: "vannes", positions: ["Arrière"], rarity: "epique", nat: "FRA" },
  { name: "Uini Atonio", team: "lapelle", clubs: ["lapelle"], positions: ["Pilier"], rarity: "legendaire", nat: "FRA" },
  { name: "Sébastien Chabal", team: "racing92", clubs: ["bourgoinjallieu","racing92"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Thierry Dusautoir", team: "toulouse", clubs: ["toulouse"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Imanol Harinordoquy", team: "biarritz", clubs: ["biarritz","toulouse"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Dimitri Yachvili", team: "biarritz", clubs: ["biarritz"], positions: ["Demi de mêlée"], rarity: "legendaire", nat: "FRA" },
  { name: "Johnny Wilkinson", team: "toulon", clubs: ["toulon"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "ANG" },
  { name: "Frédéric Michalak", team: "toulouse", clubs: ["toulouse","toulon","lyon"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "FRA" },
  { name: "Yannick Jauzion", team: "toulouse", clubs: ["toulouse"], positions: ["Centre"], rarity: "legendaire", nat: "FRA" },
  { name: "Mathieu Bastareaud", team: "toulon", clubs: ["stadefr","toulon","lyon"], positions: ["Centre"], rarity: "legendaire", nat: "FRA" },
  { name: "Virimi Vakatawa", team: "racing92", clubs: ["racing92"], positions: ["Centre"], rarity: "legendaire", nat: "FIJ" },
  { name: "Vincent Clerc", team: "toulouse", clubs: ["toulouse"], positions: ["Ailier"], rarity: "legendaire", nat: "FRA" },
  { name: "Maxime Médard", team: "toulouse", clubs: ["toulouse"], positions: ["Arrière"], rarity: "legendaire", nat: "FRA" },
  { name: "Brice Dulin", team: "lapelle", clubs: ["castres","racing92","lapelle"], positions: ["Arrière"], rarity: "legendaire", nat: "FRA" },
  { name: "Owen Farrell", team: "racing92", clubs: ["racing92"], positions: ["Demi d'ouverture","Centre"], rarity: "legendaire", nat: "ANG" },
  { name: "Siya Kolisi", team: "racing92", clubs: ["racing92"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "AFS" },
  { name: "Pita Ahki", team: "toulouse", clubs: ["toulouse"], positions: ["Centre"], rarity: "legendaire", nat: "NZL" },
  { name: "Camille Lopez", team: "bayonne", clubs: ["clermont","bayonne"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "FRA" },
  { name: "Dan Carter", team: "racing92", clubs: ["perpignan","racing92"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "NZL" },
  { name: "Christophe Dominici", team: "stadefr", clubs: ["stadefr","toulon"], positions: ["Arrière","Ailier"], rarity: "legendaire", nat: "FRA" },
  { name: "Sylvain Marconnet", team: "stadefr", clubs: ["stadefr"], positions: ["Pilier"], rarity: "legendaire", nat: "FRA" },
  { name: "Nicolas Mas", team: "perpignan", clubs: ["perpignan"], positions: ["Pilier"], rarity: "legendaire", nat: "FRA", stats: {"vitesse":68,"puissance":86,"defense":88,"passe":70,"technique":82} },
  { name: "Percy Montgomery", team: "perpignan", clubs: ["perpignan"], positions: ["Arrière"], rarity: "legendaire", nat: "AFS", stats: {"vitesse":85,"puissance":79,"defense":81,"passe":86,"technique":90} },
  { name: "Bryan Habana", team: "toulon", clubs: ["toulon"], positions: ["Ailier"], rarity: "legendaire", nat: "AFS" },
  { name: "Sergio Parisse", team: "stadefr", clubs: ["stadefr","toulon"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "ITA" },
  { name: "Brock James", team: "clermont", clubs: ["clermont"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "AUS" },
  { name: "Mario Ledesma", team: "clermont", clubs: ["clermont"], positions: ["Talonneur"], rarity: "legendaire", nat: "ARG" },
  { name: "Takudzwa Ngwenya", team: "biarritz", clubs: ["biarritz"], positions: ["Ailier"], rarity: "legendaire", nat: "USA" },
  { name: "Rodrigo Capo Ortega", team: "castres", clubs: ["castres"], positions: ["Deuxième ligne"], rarity: "legendaire", nat: "URU" },
  { name: "Johnny Sexton", team: "racing92", clubs: ["racing92"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "IRL" },
  { name: "Mamuka Gorgodze", team: "toulon", clubs: ["montpellier","toulon"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "GEO" },
  { name: "Napolioni Nalaga", team: "clermont", clubs: ["clermont"], positions: ["Ailier"], rarity: "legendaire", nat: "FIJ" },
  { name: "Lionel Nallet", team: "castres", clubs: ["castres","racing92"], positions: ["Deuxième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Louis Picamoles", team: "montpellier", clubs: ["montpellier","toulouse"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "François Steyn", team: "montpellier", clubs: ["montpellier"], positions: ["Centre"], rarity: "legendaire", nat: "AFS" },
  { name: "Carl Hayman", team: "toulon", clubs: ["toulon"], positions: ["Pilier"], rarity: "legendaire", nat: "NZL" },
  { name: "Steffon Armitage", team: "toulon", clubs: ["toulon"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "ANG" },
  { name: "Delon Armitage", team: "toulon", clubs: ["toulon"], positions: ["Arrière"], rarity: "legendaire", nat: "ANG" },
  { name: "Adam Ashley-Cooper", team: "ubb", clubs: ["ubb"], positions: ["Centre"], rarity: "legendaire", nat: "AUS", stats: {"vitesse":82,"puissance":87,"defense":85,"passe":87,"technique":86} },
  { name: "Rodrigo Roncero", team: "stadefr", clubs: ["stadefr"], positions: ["Pilier"], rarity: "legendaire", nat: "ARG" },
  { name: "Martin Scelzo", team: "clermont", clubs: ["clermont"], positions: ["Pilier"], rarity: "legendaire", nat: "ARG" },
  { name: "François Trinh-Dhuc", team: "montpellier", clubs: ["montpellier","toulon"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "FRA" },
  { name: "Conrad Smith", team: "pau", clubs: ["Pau"], positions: ["Centre"], rarity: "legendaire", nat: "NZL" },
  { name: "Guilhem Guirado", team: "perpignan", clubs: ["perpignan","montpellier","toulon"], positions: ["Talonneur"], rarity: "legendaire", nat: "FRA", stats: {"vitesse":72,"puissance":86,"defense":84,"passe":80,"technique":88} },
  { name: "Yannick Nyanga", team: "toulouse", clubs: ["toulouse","racing92"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Aurélien Rougerie", team: "clermont", clubs: ["clermont"], positions: ["Ailier"], rarity: "legendaire", nat: "FRA" },
  { name: "Juan Martin Hernandez", team: "stadefr", clubs: ["stadefr"], positions: ["Demi d'ouverture","Arrière"], rarity: "legendaire", nat: "ARG" },
  { name: "Jerome Kaino", team: "toulouse", clubs: ["toulouse"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "NZL" },
  { name: "Morgan Parra", team: "clermont", clubs: ["bourgoinjallieu","clermont"], positions: ["Demi de mêlée"], rarity: "legendaire", nat: "FRA" },
  { name: "Joe Rokocoko", team: "bayonne", clubs: ["bayonne","racing92"], positions: ["Ailier"], rarity: "legendaire", nat: "NZL" },
  { name: "Scott Spedding", team: "clermont", clubs: ["bayonne","clermont"], positions: ["Arrière"], rarity: "legendaire", nat: "FRA" },
  { name: "Dimitri Szarzewski", team: "stadefr", clubs: ["stadefr","racing92"], positions: ["Talonneur"], rarity: "legendaire", nat: "FRA" },
  { name: "Felipe Contepomi", team: "toulon", clubs: ["toulon","stadefr"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "ARG" },
  { name: "Luke McAllister", team: "toulouse", clubs: ["toulouse","toulon","clermont"], positions: ["Demi d'ouverture"], rarity: "legendaire", nat: "NZL" },
  { name: "Chris Masoe", team: "castres", clubs: ["castres","toulon","racing92"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "NZL" },
  { name: "Damien Traille", team: "biarritz", clubs: ["biarritz","pau"], positions: ["Centre/Arrière"], rarity: "legendaire", nat: "FRA" },
  { name: "Matt Giteau", team: "toulon", clubs: ["toulon"], positions: ["Demi d'ouverture/Centre"], rarity: "legendaire", nat: "AUS" },
  { name: "James O'Connor", team: "toulon", clubs: ["toulon"], positions: ["Ailier/Arrière/Demi d'ouverture"], rarity: "legendaire", nat: "AUS" },
  { name: "Metuisela Talebula", team: "ubb", clubs: ["ubb","bayonne"], positions: ["Ailier/Arrière/Centre"], rarity: "legendaire", nat: "FIJ", stats: {"vitesse":88,"puissance":86,"defense":80,"passe":90,"technique":80} },
  { name: "Sione Mafileo", team: "vannes", positions: ["Pilier"], rarity: "commune", nat: "NZL" },
  { name: "Thomas Ployet", team: "vannes", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Ray Nu'u", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "NZL" },
  { name: "Ioane Iashagashvili", team: "vannes", positions: ["Troisième ligne"], rarity: "commune", nat: "GEO" },
  { name: "Joe Jonas", team: "vannes", positions: ["Arrière"], rarity: "rare", nat: "AFS" },
  { name: "Paul O'Connell", team: "toulon", clubs: ["toulon"], positions: ["Deuxième ligne"], rarity: "legendaire", nat: "IRL" },
  { name: "Tana Umaga", team: "toulon", clubs: ["toulon"], positions: ["Centre"], rarity: "legendaire", nat: "NZL" },
  { name: "Ayamura Goromaru", team: "toulon", clubs: ["toulon"], positions: ["Arrière"], rarity: "legendaire", nat: "JAP" },
  { name: "Leigh Halphpenny", team: "toulon", clubs: ["toulon"], positions: ["Arrière"], rarity: "legendaire", nat: "PDG" },
  { name: "Drew Mitchell", team: "toulon", clubs: ["toulon"], positions: ["Ailier"], rarity: "legendaire", nat: "AUS" },
  { name: "Juan Manuel Leguizamon", team: "stadefr", clubs: ["stadefr"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "ARG" },
  { name: "Byron Kelleher", team: "toulouse", clubs: ["toulouse","stadefr"], positions: ["Demi de mêlée"], rarity: "legendaire", nat: "NZL" },
  { name: "Siteveni Sivivatu", team: "clermont", clubs: ["clermont"], positions: ["Ailier/Centre"], rarity: "legendaire", nat: "NZL" },
  { name: "Bakkies Botha", team: "toulon", clubs: ["toulon"], positions: ["Deuxième ligne"], rarity: "legendaire", nat: "AFS" },
  { name: "Julien Bonnaire", team: "clermont", clubs: ["clermont"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Martin Bustos Moyano", team: "bayonne", clubs: ["bayonne","montpellier"], positions: ["Arrière"], rarity: "legendaire", nat: "ARG" },
  { name: "Juan Martín Fernández Lobbe", team: "toulon", clubs: ["toulon"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "ARG" },
  { name: "Juan Smith", team: "toulon", clubs: ["toulon"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "AFS" },
  { name: "Census Jonhston", team: "toulouse", positions: ["Pilier"], rarity: "commune", nat: "SAM" },
  { name: "Fulgence Ouedraogo", team: "montpellier", clubs: ["montpellier"], positions: ["Troisième ligne"], rarity: "legendaire", nat: "FRA" },
  { name: "Cheslin Kolbe", team: "toulouse", clubs: ["toulouse","toulon"], positions: ["Ailier/Arrière"], rarity: "legendaire", nat: "AFS" },
  { name: "Eben Etzebeth", team: "toulon", clubs: ["toulon"], positions: ["Deuxième ligne"], rarity: "legendaire", nat: "AFS" },
  { name: "Hamish Watson", team: "castres", positions: ["Troisième Ligne"], rarity: "international", nat: "ECO" },
  { name: "Kylian Ringuet", team: "castres", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Mathys Belaubre", team: "clermont", positions: ["Centre"], rarity: "commune", nat: "FRA" },
  { name: "Fousseynou Cissokho", team: "lyon", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Israel Leota", team: "stadefr", positions: ["Ailier"], rarity: "commune", nat: "SAM" },
  { name: "Brad Amituanai", team: "perpignan", positions: ["Pilier"], rarity: "commune", nat: "AUS", stats: {"vitesse":70,"puissance":73,"defense":83,"passe":76,"technique":79} },
  { name: "Thomas Delpeuch", team: "ubb", positions: ["Ailier"], rarity: "commune", nat: "FRA", stats: {"vitesse":70,"puissance":67,"defense":68,"passe":65,"technique":70} },
  { name: "Achille Stoessel", team: "castres", positions: ["Talonneur"], rarity: "commune", nat: "FRA" },
  { name: "Théo Vidal", team: "castres", positions: ["Demi d'ouverture"], rarity: "commune", nat: "FRA" },
  { name: "Sione Ahio", team: "lapelle", positions: ["Pilier"], rarity: "commune", nat: "NZL" },
  { name: "Diego Miranda", team: "pau", positions: ["Ailier"], rarity: "commune", nat: "FRA" },
  { name: "Nicolas Martins", team: "racing92", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA" },
  { name: "Murray Taulagi", team: "vannes", positions: ["Ailier"], rarity: "epique", nat: "AUS" },
  { name: "Inia Tabuavou", team: "vannes", positions: ["Centre"], rarity: "commune", nat: "FIJ" },
  { name: "Charles Kanté-Samba", team: "lapelle", positions: ["Deuxième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":65,"puissance":75,"defense":72,"passe":68,"technique":70} },
  { name: "Lucas Andjisseramatchi", team: "lapelle", positions: ["Troisième ligne"], rarity: "commune", nat: "FRA", stats: {"vitesse":70,"puissance":82,"defense":78,"passe":69,"technique":77} },
];

const RARITIES = {
  "commune": { label: "Commune", color: "#9e9e9e", weight: 60, sellValue: 5, noteMin: 40, noteMax: 64 },
  "rare": { label: "Rare", color: "#05DF72", weight: 27, sellValue: 20, noteMin: 65, noteMax: 76 },
  "epique": { label: "Épique", color: "#9c27b0", weight: 10, sellValue: 75, noteMin: 77, noteMax: 85 },
  "international": { label: "International", color: "#1a1a2e", weight: 3, sellValue: 200, noteMin: 86, noteMax: 92 },
  "legendaire": { label: "Légende", color: "#ffd700", weight: 0, sellValue: 500, noteMin: 93, noteMax: 99 },
};

const PACKS = [
  { id: "standard", name: "Pack Nationale", description: "5 cartes — chances équilibrées", cardsCount: 5, cost: 100, weightModifier: {"commune":1,"rare":1,"epique":1,"international":1,"legendaire":0} },
  { id: "premium", name: "Pack Pro D2", description: "5 cartes — meilleures chances de Rare+", cardsCount: 5, cost: 250, weightModifier: {"commune":0.4,"rare":1.5,"epique":1.8,"international":1.5,"legendaire":0} },
  { id: "legendaire", name: "Pack TOP 14", description: "3 cartes — au moins une Épique garantie", cardsCount: 3, cost: 500, guaranteedRarity: "epique", weightModifier: {"commune":0.1,"rare":1,"epique":2.5,"international":3,"legendaire":0} },
  { id: "international", name: "Pack Légende", description: "1 carte — un joueur Légende garanti", cardsCount: 1, cost: 1000, forcedRarity: "legendaire" },
  { id: "xv_demarrage", name: "Pack XV Démarrage", description: "15 cartes de départ — GRATUIT — 1 seule fois", cardsCount: 15, cost: 0, oneTime: true, locked: true },
  { id: "coup_envoi", name: "Pack Coup d'Envoi", description: "Disponible 1 fois par jour — GRATUIT", cardsCount: 1, cost: 0, daily: true, locked: true },
];
